### ISSUE TITLE
Change the endings -us to make the PLURAL for SUBJ PERFECT 3rd conjugation PASSIVE voice

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#101]
-us sīmus should be -ī  sīmus
-us sītis   should be   -ī sītis
-us sint   should be   -ī sint
PLURAL SUBJ PERFECT 3rd conjugation PASSIVE voice

**Comment by balmas** [comment]
@monzug this can now be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-3

**Comment by monzug** [comment]
Fixed.
