### ISSUE TITLE
Please correct the ending -iāatis 4th conjugation ACTIVE voice

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#102]
-iāatis should be -iātis
2nd person plural SUBJ PRESENT active voice 4th conjugation

**Comment by balmas** [comment]
this was done in ab4413dd57dcb816ff06086ef5704d75d81fcebd

**Comment by balmas** [comment]
@monzug this can now be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-3

**Comment by monzug** [comment]
Fixed.
