### ISSUE TITLE
4th coniugation verb: present stem audī

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#103]
endings in the inflection table are correct but Whitaker uses a different present stem.
e.g. vinciebamus   or audiebamus
Whitaker
vinci.ebamus         V      4 1 IMPF ACTIVE  IND 1 P    
vincio, vincire, vinxi, vinctus  V   [XXXBX]  
bind, fetter; restrain;

Allen&Greenough  and the inflection table have the ending -iēbāmus

No match here for vinciēbāmus or audiēbāmus. this is true for all the matches in the Active and Passive voice using the present stem.

**Comment by balmas** [comment]
I believe this will be fixed when we fix #91

**Comment by balmas** [comment]
Fix is in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-7

**Comment by monzug** [comment]
we have exact matches for the two verbs above, plus audiar, audirer, audiatur, audiebam etc.
