### ISSUE TITLE
Perfect & Supine stem for 4th conjugation should be changed to reflect traditional grammars

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#104]
see related issues #84 and #93

The endings in the inflection table for the ACTIVE and PASSIVE voices of the 4th conjugation
for the perfect and supine stem need to be updated.
e.g.   vinxi
vinx.i               V      4 1 PERF ACTIVE  IND 1 S    
vincio, vincire, vinxi, vinctus  V   [XXXBX]  
bind, fetter; restrain;
no match as the inflection table for the PERF ACTIVE IND 1 S is -īvi   
It should be -ī  accordingly also to Allen & Greenough
Please, remove the -īv in the endings with perfect stem and remove the -īt in the endings with the supine stem.

some accents need to be fixed, such as
īti erātis  should be ī erātis
īti essētis should be ī essētis
īti essent should be ī essent

**Comment by balmas** [comment]
@monzug re this: "remove the -īt in the endings with the supine stem." Do you mean the pluperfect stem?

**Comment by monzug** [comment]
guess you found the answer!!! I am using Allen&Greenough's terminology and
they call it supine stem

**Comment by balmas** [comment]
@monzug this can now be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-3

**Comment by monzug** [comment]
still few endings need to be updated:
1) FUT. PERF. passive voice  (supine stem, e.g. audit-)
2) the singular pluperfect indicative

**Comment by monzug** [comment]
looks good. thanks
