### ISSUE TITLE
add conjugation table for prodsum

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#117]
forked from #70

**Comment by monzug** [comment]
need to investigate if whitaker does recorgnize this verb. I search for prodsum but it gave back the verb sum + participle

**Comment by monzug** [comment]
Whitaker ignores prodsum.  in Allen & Greenough, prodsum is a earlier form of prosum. Maybe we should just add a footnote somewhere. need to think what and where

**Comment by monzug** [comment]
the footnote should says: pro (earlier form prod,retains its original d before e)

**Comment by balmas** [comment]
that sounds fine to me @monzug . Should I assign this to you to do?

**Comment by monzug** [comment]
yes please

**Comment by monzug** [comment]
added footnotes 14 to forms.csv and to form_footnotes.csv. I did also edit the footnotes.csv then realized that I should use the other file for irregular verb. could you pls undo (or ignore my request to master) for footnotes.csv? I am not sure how to undo an editing. THANKS!!!

**Comment by monzug** [comment]
Thanks

**Comment by balmas** [comment]
@monzug the table should be there in build 2.1.0.14 (https://github.com/alpheios-project/webextension/tree/issue-176/dist) but you can't get to it from the inflection browser because I forgot to add it there. Not sure if you can test it otherwise?

**Comment by balmas** [comment]
oh, nevermind, I see that we don't have a table for prodsum, just a footnote. Will fix the truncation on the footnote.

**Comment by monzug** [comment]
fixed! Thanks
