### ISSUE TITLE
add conjugation table for subsum

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#118]
forked from #70

**Comment by monzug** [comment]
added to data table

**Comment by balmas** [comment]
this is in build 2.1.0.12 and ready for testing. Still needs to be merged to master if testing is ok.

**Comment by balmas** [comment]
merged and in inflection browser in build 2.1.0.13 (available from https://github.com/alpheios-project/webextension/tree/release-2.1.0.x)

**Comment by monzug** [comment]
Please use the updated file on next build. Thanks

**Comment by balmas** [comment]
in build 2.1.0.14

**Comment by monzug** [comment]
looks good
