### ISSUE TITLE
can't find the close button for footnotes 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#126]
when footnotes are in the last column of the related inflection table, the close button is not visible. Only by enlarging the window a lot, the close button is visible. not sure if it's possible to have the footnotes as pop-ups with the frame inside the active window. both in chrome and firefox.
see screenshot
![screenshot_2018-08-28 screenshot](https://user-images.githubusercontent.com/41396793/44734458-f753c700-aab7-11e8-8bb5-8edfcdc8659b.png)

**Comment by irina060981** [comment]
Added draggable behaviour to footnote popup - 
https://github.com/alpheios-project/components/pull/181

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-4

**Comment by balmas** [comment]
@monzug actually what Irina did to address this was to make the footnotes draggable so that you can drag to see the full note and the close icon. Does that work for you?

**Comment by balmas** [comment]
Comment from @monzug : the dragging behavior works fine, but it would still be nice if we could adjust the placement of the footnote popup so that it isn't off screen. Is there an easy fix for this?

**Comment by irina060981** [comment]
Fixed - created PR - https://github.com/alpheios-project/components/pull/202
Changing translationX according to the infl popup placement:

original - **center** (translateX(-50%))
![image](https://user-images.githubusercontent.com/12377640/45407345-7ea25c80-b6ac-11e8-9169-e66db0d04787.png)

new - **left** (translateX(0))
![image](https://user-images.githubusercontent.com/12377640/45407289-51ee4500-b6ac-11e8-9a86-fcfc999b7427.png)

new - **right** (translateX(-100%))
![image](https://user-images.githubusercontent.com/12377640/45407369-911c9600-b6ac-11e8-8491-2c742bfe58aa.png)

@monzug , you could check in this branch -  
https://github.com/alpheios-project/webextension/tree/qa-check-infl-popup-align

**Comment by monzug** [comment]
Thanks! tested in Chrome
