### ISSUE TITLE
please correct the ending issēm in the 1st person Plural Sub Plup for the 1st conj

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#132]
it should be -issemus
e.g.
amav.issemus         V      1 1 PLUP ACTIVE  SUB 1 P    
amo, amare, amavi, amatus  V   [XXXAO]  
love, like; fall in love with; be fond of; have a tendency to;

see issue #84

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-4

**Comment by monzug** [comment]
Thanks. I can see a beautiful match now...
