### ISSUE TITLE
itum and itu supine are missing verb irregular 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#133]
the supine itum and itu don't have an exact match on the supine table. it says only verb , not verb irregular

whitaker output:
it.um                VPAR   6 1 NOM S N PERF PASSIVE PPL
it.um                VPAR   6 1 VOC S N PERF PASSIVE PPL
it.um                VPAR   6 1 ACC S M PERF PASSIVE PPL
it.um                VPAR   6 1 ACC S N PERF PASSIVE PPL
it.um                SUPINE 6 1 ACC S N                 
eo, ire, ivi(ii), itus  V   [XXXAX]  
go, walk; march, advance; pass; flow; pass (time); ride; sail;
it.um                N      4 1 ACC S M                 
itus, itus  N  M   [XXXCX]  
going, gait; departure;

**Comment by balmas** [comment]
I think this will be fixed with #90

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-5

**Comment by monzug** [comment]
yes. fixed in build 2.0.2-5 - tested in Chrome
