### ISSUE TITLE
greek adjective 3rd declension is missing from the table

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#135]
For some reason the 3rd declension adjective endings are missing from the Greek adjective inflection table. I think it has to do with the combined genders but I haven't been able to isolate the exact cause yet. One thing to note is that the Greek adjective data for the 3rd declension has endings with only feminine gender and with feminine masculine.

@kirlat can you look at this when you have a second?

**Comment by kirlat** [comment]
Checking it now ...

**Comment by monzug** [comment]
got an error: manifest file missing or unreadable. would it work if I only copy the dist folder over the regular build and reinstall it? thanks

**Comment by kirlat** [comment]
@monzug, it is my bad again. The correct link should be https://github.com/alpheios-project/webextension/archive/infltbl-i135.zip.

**Comment by monzug** [comment]
No problem at all. gonna try this one right now. Thanks.

**Comment by monzug** [comment]
tested for ἑκών   ->   adj of 3rd decl. table is shown properly (not match though...)
and for μέλαιναι  (match found!)
also double clicking an adjective of 1st/2nd decl  (e.g. οἶον ) it will show the 3rd decl column in the full table

**Comment by monzug** [comment]
Finally I found the original bug where I reported this issue, bug #60
