### ISSUE TITLE
Font looks weird in definitions for specific site

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#136]
In http://www.poesialatina.it/_ns/Greek/testi/Homerus/Odyssea01.htm, the definitions looks weird as the font and alignment are all screwed up. see screenshot. both in Chrome and Firefox.
Again, I have seen this only on this site so far.
![screenshot_2018-09-01 homerus-odyssea i](https://user-images.githubusercontent.com/41396793/44948171-0c499680-ade7-11e8-96b3-78120cd974b8.png)

**Comment by balmas** [comment]
assigning to @irina060981 . Must be a base style scenario missed in our normalization?

**Comment by irina060981** [comment]
@balmas, It is an example when styles applied directly to tags without any classes and id:
![image](https://user-images.githubusercontent.com/12377640/45010364-7d3fb700-b050-11e8-9339-04d73c1dd52b.png)

**Comment by irina060981** [comment]
I have added normalization for i,b,u tags - now it look ok

![image](https://user-images.githubusercontent.com/12377640/45010734-44084680-b052-11e8-9fab-e00997831c98.png)

**Comment by irina060981** [comment]
merged

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-4

**Comment by monzug** [comment]
tested in firefox. looks good. Thanks. will retest in final build both in firefox and chrome
