### ISSUE TITLE
Greek relative pronoun has only the neuter gender

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#148]
tested in Chrome in build 2.0.3-5
double-click on ἥν   from  http://www.poesialatina.it/_ns/Greek/testi/Homerus/Odyssea01.htm
we do not have a match as the fem and masc gender in the table are missing
![greek-pronoun](https://user-images.githubusercontent.com/41396793/45438058-1f305680-b684-11e8-9572-4092b2db5a0b.JPG)

**Comment by kirlat** [comment]
This probably has been fixed during works for alpheios-project/components#40. Please test it with the latest build of that branch: https://github.com/alpheios-project/webextension/archive/comp-i40.zip.

In my tests it was showing correctly, please see an image below:
![image](https://user-images.githubusercontent.com/18631055/45474452-dc858180-b74a-11e8-9d82-f7e2762d4d18.png)

**Comment by monzug** [comment]
I read briefly #40 and it does need accurate testing so I will wait for the ok from Bridget. Thanks

**Comment by monzug** [comment]
YES! I can see the full table. Thanks
