### ISSUE TITLE
Greek pronoun: οἷ  vs  οἳ

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#149]
from http://www.poesialatina.it/_ns/Greek/testi/Homerus/Odyssea01.htm, double click on the Greek word
οἷ on row 8. the morphology panel says that it's - a pronoun with meaning him, her - a pronoun with meaning this, that - an article. there are only two inflection tables opened: 1) the article 2) the Relative pronoun table. I was expecting to have a match also in the Personal pronoun table.
Looking at the pronoun in the related tables (and at the online grammar) they have a different accent 
οἷ  vs  οἳ  
with οἷ  -> personal pronoun   and    οἵ  -> relative pronoun
so, is there an error in the morphology output?
and why do we generate only the relative table?

**Comment by balmas** [comment]
this is at least in part due to incomplete implementation of #60. Working on fixing that and then will see if other errors remain.

**Comment by balmas** [comment]
Fixed via alpheios-project/data-models#56

**Comment by balmas** [comment]
fix is in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-7

**Comment by monzug** [comment]
yes! I have both table available in drop-down + exact matches
