### ISSUE TITLE
the order of gender should be f.m.n. in Greek tables

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#154]
We changed the order to be f.m.n. in the Latin. we might want to consider doing it for the Greek for consistency.

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-8

**Comment by monzug** [comment]
how about the order in the Greek tables: it's m. and then f. in the column in the pronoun and noun declension tables?

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-10/dist
