### ISSUE TITLE
Latin: change m./f. to f./m. in noun declension table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#155]
as we changed the gender's order to be f.m.n., we should also update the noun declension table to say f./m.

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-8

**Comment by monzug** [comment]
2 questions:
1) how about the order in the Greek tables: it's m.  and then f. column in the pronoun and noun declension tables?
2) in morphology, we do also display the m. before the f.. should we keep it this way or should this also be changed? e.g. greek pronoun οἳ  is  s. dat (m) dat (f)

**Comment by monzug** [comment]
I move the first question to the Greek related issue #154

**Comment by balmas** [comment]
hmm. I think we could change that but I would say it's not critical for the release. Do you agree?

**Comment by monzug** [comment]
agree, absolutely not critical at all.

**Comment by balmas** [comment]
ok, that's now requested in #172

**Comment by monzug** [comment]
perfect
