### ISSUE TITLE
Greek: I would add an other ending to the Plural Accusative 3rd declension

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#157]
comparing endings and grammars, I realize that there is never a definitive answer with Greek. said so, can we add an ending to the Plural Accusative 3rd declension f./m.?
the ending would be ᾰς for φῠ́λᾰκᾰς 
I am not sure if by suppressing the accents, there will still be an exact match as the morphology has ending in κᾰς, or if we will have a match by implementing fix 91.
In a way it's not a big deal, but for accuracy I would do it as it's an ending in two grammars.

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-8

**Comment by monzug** [comment]
Thanks. Checked both endings and they are in.
