### ISSUE TITLE
Greek pronouns should include person in morphology match list

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#165]
e.g.  ἡμεῖς has 1st, 2nd and 3rd person highlighted cells.  also, οἷ  has exact matches + 1st, 2nd and 3rd person highlighted cells
@balmas need help on this one!
In the morphology we do not have 1st, 2nd and 3rd person but gender, so this might cause the extra highlighting of cells.

_Originally posted by @monzug in https://github.com/alpheios-project/inflection-tables/issues/159#issuecomment-423158934_

**Comment by balmas** [comment]
wait , I am not done!
let's go back to οἳ - article and personal pronoun and relative pronoun. it looks like the personal and relative pronoun are highlighting the same cells. Note that exact matches are displayed correctly.

pronoun personal s. dat f.m. -> highlighted all cells with with s. dat m.f.n. + PLURAL NOMINATIVE
pronoun relative p. nom, m. -> highlighted cells in p. nom. m. and SINGULAR DATIVE m. and f.
it looks like the two tables have been merged.

**Comment by monzug** [comment]
and last, lookup for οἷ
it's article and personal pronoun. when I look at the pronoun table drop-down, there is also the relative pronoun table which should not be there (and if you look at the highlight cells is pretty interesting too)

![screenshot_2018-09-20 homerus-odyssea i 1](https://user-images.githubusercontent.com/41396793/45819566-a435f400-bcb2-11e8-8f46-9f7227c1e304.png)

**Comment by balmas** [comment]
that last one is very weird indeed.  I will investigate

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-10/dist

But note: This only fixes the problem if the morphology data actually includes the person information, as in the case of ἡμεῖς

For the second case mentioned, οἳ, the morphological data doesn't include person, so , according to the rules we have, the cells with person are still considered a match. I want to postpone addressing that case, because sometimes we need it to work that way, and I think it could break too much to change right now.

**Comment by balmas** [comment]
@monzug I get an exact match on ἡμεῖς. Can you still reproduce? Might be one of those transitory state errors? Can you reproduce?

**Comment by monzug** [comment]
confirm - exact match on ἡμεῖς

do we leave this open for second issue?

**Comment by balmas** [comment]
no, let's close it. I have entered #182 for the 2nd issue.

**Comment by monzug** [comment]
ok
