### ISSUE TITLE
irregular verb participle table showing up when it shouldn't

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#168]
lookup venit
it matches 2 lexemes, a regular and an irregular verb. the regular verb is venio, and the irregular verb is veneo, for which we don't have a table. Select the verb-irregular drop down and you see the participle table for all the irregular verbs, but no irregular table. 

I think this is happening because of the multiple lexemes in the homonym, because if you lookup veneo by itself, for which we don't get the regular verb venio in the homonym, you correctly get the "unimplemented table" message when you select verb-irregular in the dropdown.

**Comment by kirlat** [comment]
The fix build is https://github.com/alpheios-project/webextension/archive/infltbl-i167.zip, it should be working as expected (at least it does to me). Please see comments to #167 for more details.

**Comment by balmas** [comment]
this is now in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-14/dist

**Comment by monzug** [comment]
this works for venit.
