### ISSUE TITLE
translation for Greek pronoun

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#171]
lookup the Greek personal pronoun σφῷν  -> the translation field has some other content in it
Not sure if there is anything that can be done to this

see screenshot
![translation-pronoun](https://user-images.githubusercontent.com/41396793/45831398-44991200-bccd-11e8-9caf-834efb5ecb93.png)

**Comment by balmas** [comment]
ah, that's bad data in our Greek short defs file. Nice catch! Easy to fix.

**Comment by balmas** [comment]
this is fixed by https://github.com/alpheios-project/lsj/commit/48178d6a2680d7fb543a503fcbbf6b519e678c01 . Changed short definition to "they,them". You will need to restart your browser and clear your cache to make sure to pick up the new definitions because they get cached.

**Comment by monzug** [comment]
Now translation says they, them. THANKS!
