### ISSUE TITLE
are the inflection tables for forms of fero correct?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#180]
@kirlat notes that forms of fero (e.g. feramus) result in both the regular and irregular verb table.  It is identified by the parser as a 3rd conjugation verb, but we have it as a lemma in our irregular verb data. Are we handling the tables for this verb correctly?

**Comment by kirlat** [comment]
Some technical details about our algorithm that determines whether a word is regular or irregular. 

From morph analyzer adapter data we cannot usually say if a verb is regular or irregular, with some exceptions where it sets conjugation. For irregular verbs we can check if we have their forms in our CSV data. This is a pretty straightforward test. But we have no formal test to determine if the word is "regular". What we do is check if there are any suffix matches in our CSV data and if we do have them, we assume this word is regular and we produce regular (verb) tables for it.

In our current code we check if the word is irregular first, and then we do a check for any suffix matches, which is our current test for "regularity".

So there could be two scenarios:
S1. Test for irregularity fails. Then we check for matching suffixes and if there are any, we assume that `regular` is true and `irregular` is false for a word.
S2. Test for irregularity succeeds. This means that `irregular` is true. Shall we assume then that this word is irregular only, or shall we still check for regularity (suffix matches) too? If there are any suffix matches shall we then set both `regular` and `irregular` to true? This will result in both regular and irregular verb tables shown for a word.

If a word is "pure irregular", are there any situation where we would like to show a regular verb tables for it?

**Comment by monzug** [comment]
The number of irregular verbs vary from grammar to grammar. Some grammars like Whitaker defines fero as 3rd conj verb because some forms of fero follow the regular inflection of verbs of the 3rd conjugation.
can we postpone this one for after the release and we can discuss all the implication?

**Comment by kirlat** [comment]
Thank you for clarifications! I was waiting for this to finish fixes for #167 and #168. 

I will submit them with the current behavior unchanged, where we do show both regular and irregular verb tables together for such words as 'fero'.

**Comment by balmas** [comment]
Closing this. I think we are okay with the tables for fero.
