### ISSUE TITLE
Latin Participles table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#181]
Please update the following endings to the Latin Participles table
ACTIVE

1st conj
future  
ūrus, a, um    not  aturus, a, um

2nd conj
present
entis and not ventis 

future  
ūrus, a, um    not  turus, a, um

3rd conj
future  
ūrus, a, um    not  turus, a, um

4th conj
future  
ūrus, a, um    not  iturus esse

PASSIVE

1st, 2nd, 3rd and 4th conj
perfect
should be  -us, a, um

the 3rd conj passive future (gerundive) does only say endus  - I believe it should also be endus,a,um but I could not find any other grammar with this information so I would leave as is, right now and keep it as a reminder to search more carefully.

**Comment by balmas** [comment]
this can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-14/dist

**Comment by monzug** [comment]
this is fixed. I keep it assign to myself for investigating the gerundive.

**Comment by monzug** [comment]
found this:
endus, a, um
Also called the gerundive, the future passive participle is used with sum and the dative of agent to form the passive periphrastic.  Examples: mihi fugiendum est (“I must flee”), milēs explōrātōrī sequendus est (“The spy must follow the soldier”).

**Comment by monzug** [comment]
it should be -endus, a, um
