### ISSUE TITLE
lātus, -ta, -tum  passive perfect participle + ferundus (gerundive)  of fero

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#184]
I think it should be lātus, -a, -um  - in the grammar I did only find lātus but I would update them anyway because it's a mistake.
and the gerundive should ferendus   and not ferundus    (Allen&Greenough)

also, could you please change the order for consistency with the regular participle table?
PRESENT
PERFECT
FUTURE

**Comment by balmas** [comment]
this is available for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-15/dist
Note that I have also split  "lātus, -a, -um" into 3 separate forms, so that matching can actually work.

**Comment by monzug** [comment]
thanks for fixing this.
question: for all participles we have the ending in -us,-a,-um and we do have the exact match or at least for the one that I have tested (e.g. audenda, amata).
what is different with latus, a um?

**Comment by balmas** [comment]
latus, a, um was in the data as a single string, rather than as separate data items.
