### ISSUE TITLE
Vultis, vis, vult do not have a match on the Irregular volo table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#186]
volo is an irregular verb with its own table. the third person SINGULAR INDICATIVE is vult (volt), vultis is second person PLURAL INDICATIVE, and vis is second person SINGULAR - see Whitaker output

vult                 V      6 2 PRES ACTIVE  IND 3 S    
vult  X   [XXXAX]  
be willing; wish;

vultis               V      6 2 PRES ACTIVE  IND 2 P    
vultis  X   [XXXAX]  
be willing; wish;

lookup for vultis or vult  or vis, it gives table not been implemented yet. 

Whitaker output for  volo
vol.o                V      6 2 PRES ACTIVE  IND 1 S    
volo, velle, volui, -  V   [XXXAX]  
wish, want, prefer; be willing, will;

**Comment by balmas** [comment]
yes, for some reason Whitaker doesn't associate 'vult' 'vultis' and 'vis' with the 'volo' hdwd but instead just repeats the form.  I will enter this as a Whitaker bug in the morphsvc repo. We could work around it by either duplicating the volo table data for vult, vultis and vis or adding these as alternative lemmas for it (which would require a code change to allow multiple lemmas to match a single lemma-filtered table.)

**Comment by balmas** [comment]
the workarounds I suggested are really awful. Maybe it would be better actually to correct this in the morph-client, to just override the Whitaker headword for these forms.  I think I would be willing to do that.  Need to figure out which release to target it for.

**Comment by balmas** [comment]
closing this. we will address with improved morphology as described above.
