### ISSUE TITLE
lemma is missing from the irregular verb table

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#187]
We seem to have lost the lemma/principal parts at the top of the Latin irregular verb table at some point. Reported by @abrasax

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/memleaks2/dist

**Comment by monzug** [comment]
lemma is in - tested in Chrome for possunt. However we have a side effect of the irregular table not displaying correctly. Not sure if this is the cause of it or some other change.
see screenshot

![possunt](https://user-images.githubusercontent.com/41396793/46338600-9a8b8500-c5fe-11e8-97ef-b191eb8b49ce.JPG)

**Comment by monzug** [comment]
now reported in issue #198. close this one.
