### ISSUE TITLE
need to show irregular verb table before regular

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#188]
I know we pushed off getting the sort order of the inflection tables exactly right, but when we have an irregular verb without any other lexemes which are regular, as in the case of possunt, we need to show the irregular table before the regular one, otherwise it's confusing. (At one point, we were not showing the regular table at all in this scenario, so I'm not sure when that change came in).

Reported by @abrasax

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/memleaks2/dist

**Comment by monzug** [comment]
verb-irregular is listed on top of drop-down. tested in Chrome for possunt, fueris, ferebar, ibat, proderamus,
abfuimus
