### ISSUE TITLE
lookup for escunt generates an empty pop-up

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#189]
escunt is an old form of erunt.
the lookup does not produce any result. Not sure if there is anything we can do about it.

from Whitaker output
escunt
sc                   SUFFIX                             
begin to -, grow - (Inceptive or Inchoative);
esc.unt              V      3 1 PRES ACTIVE  IND 3 P    
eo, eare, evi, etus  V   [FXXFZ]    Medieval  very rare
go, walk; march, advance; pass; flow; pass (time); ride; be in the middle;

**Comment by balmas** [comment]
Moved this to https://github.com/alpheios-project/morphsvc/issues/13
