### ISSUE TITLE
Greek footnotes are missing reflink text

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#195]
The V1 tables cross-linked to the Smyth grammar via reflinks. When we converted the data we lost the links as well as the link text.

**Comment by balmas** [comment]
fixed with #196

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/memleaks2/dist

**Comment by monzug** [comment]
yes, footnotes look good now. check footnotes 31,31, 55 etc. the do have the reference to Smyth and the related section
