### ISSUE TITLE
add stem to verb tables

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#20]
add the verb stem below the conjugation header in the verb tables

**Comment by balmas** [comment]
@kirlat the stemtable can be found in the original alph-verb-conj.xml:

```
<stem-table>
            <stem conj="1st">ā</stem>
        <stem conj="2nd">ē</stem>
        <stem conj="3rd">e</stem>
        <stem conj="4th">i</stem>
    </stem-table>
```

Note also that for the ordinals (conjugation and declension) when used as headers of the inflection tables we want to spell those out (1st s/b First and so forth). This should probably be handled via the localization library.

**Comment by kirlat** [comment]
These two commits should take care of that: 9fdc960aeeb14543011daa62ef9ddbd6a4d2fa9a, 55a1762fb564444151c44bf20f5d20347e842c20.

**Comment by balmas** [comment]
looks great.
