### ISSUE TITLE
some tables have more headers than data

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#203]
this causes the collapse/expand button to be miscalculated
e.g. see  mellitisque
it has headers for 4th and 5th declension.  These never get displayed because they have no data, but they are included in the calculation of whether the table can collapse or expand.

**Comment by balmas** [comment]
it affects all latin adjectives

**Comment by kirlat** [comment]
Should be fixed in https://github.com/alpheios-project/webextension/archive/infltbl-i203.zip.
Please note that we need to retest collapse/expand button on all table types, both Latin and Greek, as all of them are affected.

**Comment by monzug** [comment]
there is a little issue with expand/collapse.
lookup 'primus'. go to the noun inflection table and expand it. then go to the adjective and the button is COLLAPSE, note that it does only display the 1st/2nd decl table, so it should be EXPAND. click on Collapse button but it does not do anything, except changing the button. only in the next click, I am able to see the expanded table.
also, caribus. if I expand the first table, then the verb table has the status of the button set to COLLAPSE.
we did have a similar issue in the past.
![collapse-expand](https://user-images.githubusercontent.com/41396793/46430616-87200d00-c717-11e8-9cc3-44464675aa93.JPG)

**Comment by balmas** [comment]
I don't know. Am tempted to leave it but will see if I can get a fix by early tomorrow. At this point we won't release until next week anyway I guess, because you need to do regression testing, and so if we can fix before you start tomorrow it might be worth it. do you agree?

**Comment by monzug** [comment]
uhm, I am pretty sure we had a fix for this in the past. maybe the fix is
not in or didn't work or I didn't test it.

**Comment by monzug** [comment]
state conflicts with Expand/collapse when browsing the Inflection tables
#173 maybe

**Comment by balmas** [comment]
yeah not sure it's the same issue as that though. Might be a different variation that was previously hidden by other bugs.

**Comment by balmas** [comment]
I'm moving this to a new issue as it's unrelated to this change. Can we mark this one closed and verified?

**Comment by monzug** [comment]
nope. I need to check the Greek tables that I haven't. will do tomorrow
morning

**Comment by monzug** [comment]
tested in Chrome for Latin and Greek in QA-20. mellitisque and caribus look good now.
