### ISSUE TITLE
expand/collapse state broken when switching views

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#206]
lookup 'primus'. go to the noun inflection table and expand it. then go to the adjective and the button is COLLAPSE, note that it does only display the 1st/2nd decl table, so it should be EXPAND. click on Collapse button but it does not do anything, except changing the button. only in the next click, I am able to see the expanded table.
also, caribus. if I expand the first table, then the verb table has the status of the button set to COLLAPSE.
we did have a similar issue in the past.
![collapse-expand](https://user-images.githubusercontent.com/41396793/46430616-87200d00-c717-11e8-9cc3-44464675aa93.JPG)

_Originally posted by @monzug in https://github.com/alpheios-project/inflection-tables/issues/203#issuecomment-426743079_

**Comment by balmas** [comment]
I believe this is fixed in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-20/dist

**Comment by monzug** [comment]
tested in Chrome both Latin and Greek in QA-20. fixed
