### ISSUE TITLE
 an extra highlighted cell when lookup for "λελύκατε" ( λελυκ - ατε )

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#207]
οἴκοι is 3rd person sing. PERF. OPT. ACT. we don't have a match in the PERFECT ACTIVE SYSTEM inflection table. Any verb in the Optative (simple) table does not have a match.

Note that the last 3 tables are not shown in the web browser when expanding the Perfect Active System. This has been reported previously but I could not find any reference.

also, there is an extra highlighted cell when lookup for "λελύκατε" ( λελυκ - ατε )
see screenshot
![greek-verb-no-match](https://user-images.githubusercontent.com/41396793/46528105-ef2e3a80-c860-11e8-9a38-08922bca0f9c.JPG)

**Comment by balmas** [comment]
> οἴκοι is 3rd person sing. PERF. OPT. ACT. we don't have a match in the PERFECT ACTIVE SYSTEM inflection table. Any verb in the Optative (simple) table does not have a match.

This is a duplicate of #152. Will add this as a test case there.

**Comment by balmas** [comment]
>Note that the last 3 tables are not shown in the web browser when expanding the Perfect Active System. This has been reported previously but I could not find any reference.

This is #225  now.

**Comment by balmas** [comment]
this item now only addresses the last point: 

>also, there is an extra highlighted cell when lookup for "λελύκατε" ( λελυκ - ατε )

and I've changed the title accordingly.

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment]
Thanks.
