### ISSUE TITLE
matches highlighted for sum in the regular verb table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#209]
lookup for sum. from Whitaker
s.um                 V      5 1 PRES ACTIVE  IND 1 S    
sum, esse, fui, futurus  V   [XXXAX]  
to be, exist; also used to form verb perfect passive tenses with NOM PERF PPL
*
in the morphology, we do have two other entries (where are these two entries coming from?):
1) sumo, sumere, sumpsi, sumptus
sum
verb 3rd conj
2nd person sing. pres. imp. active
2)  sumo, sumere, sumsi, sumtus
sum
verb 3rd conj
2nd person sing. pres. imp. active

In the imperative table we do have the cell highlighted for the 2nd person pres. imp. active. this is ok.  We do also have matching ending for - in the 2nd plural passive for all conj.

in the regular verb table, we do have highlighted all matching ending in "-".  this one I don't get it.

One more question: in the verb drop-down, shouldn't be verb-irregular before imperative?

**Comment by balmas** [comment]
>in the morphology, we do have two other entries (where are these two entries coming from?):
sumo, sumere, sumpsi, sumptus
sum
verb 3rd conj
2nd person sing. pres. imp. active
sumo, sumere, sumsi, sumtus
sum
verb 3rd conj
2nd person sing. pres. imp. active

Our version of Whitaker gives us these additional lemmas. There are various versions out there and I am not sure if this was a fix we added to it so many years ago or if the lack of it indicates a fix someone else added.

**Comment by balmas** [comment]
>in the regular verb table, we do have highlighted all matching ending in "-". this one I don't get it.

We highlight this because of the 3rd lemma reported by Whitaker:

sum
verb 3rd conj
2nd person sing. pres. imp. active

which has no ending. The - matches no ending.

**Comment by balmas** [comment]
>One more question: in the verb drop-down, shouldn't be verb-irregular before imperative?
I went by the order we had in Alpheios V1, which had the participle, supine, infinitive and imperative all coming before irregular.

**Comment by monzug** [comment]
No issue here. closed
