### ISSUE TITLE
show paradigm tables for all lexemes

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#210]
Lookup for  ποιῶ   or   ποιοῦμεν - both are verbs of Present System Active of Contract Verbs in -έω  and  Present System Active of Contract Verbs in -όω. We have the matches only in the latest table. The Present System Active of Contract Verbs in -έω  is not displayed.

**Comment by monzug** [comment]
there is a similar scenario for  πλεῖ  - it should also open the  Present System Active of Contract Verbs in -έω (monosyllabic stems)  but it does only open the Present System Middle-Passive of Contract Verbs in -έω (monosyllabic stem  table.

**Comment by balmas** [comment]
confirmed that we seem not to be handling multiple lexemes properly for the paradigms

**Comment by monzug** [comment]
I have a note for ἔθετο - we only show ω-Verbs: Present System Middle-Passive table but it's also aorist ind. mid.
moved from #216

**Comment by balmas** [comment]
> I have a note for ἔθετο - we only show ω-Verbs: Present System Middle-Passive table but it's also aorist ind. mid.
> moved from #216

ἔθετο is yet a different issue :-) we seem to be missing all of the τίθημι aorist system middle matches due to a typo in the rules (looking for stemtype emi_or instead of emi_aor)

**Comment by monzug** [comment]
lost in translation....

**Comment by balmas** [comment]
sorry!

we use the value of the stemtype field in the whitaker's output to help us match a verb to the correct paradigm table.  The rules for that table said to match on a value of emi_or  but it should have been emi_aor.

E.g. 
http://morph.alpheios.net/api/v1/analysis/word?word=%E1%BC%94%CE%B8%CE%B5%CF%84%CE%BF&lang=grc&engine=morpheusgrc

returns 
```
 ...
 <oac:Body rdf:about="urn:uuid:idm139952568805224">
      <rdf:type rdf:resource="cnt:ContentAsXML"/>
      <cnt:rest xmlns:cnt="http://www.w3.org/2008/content#">
        <entry uri="">
          <dict>
            <hdwd xml:lang="grc">τίθημι</hdwd>
            <pofs order="1">verb</pofs>
          </dict>
          <infl>
            <term xml:lang="grc">
              <stem>ἐ:θ</stem>
              <suff>ετο</suff>
            </term>
            <pofs order="1">verb</pofs>
            <mood>indicative</mood>
            <num>singular</num>
            <pers>3rd</pers>
            <tense>aorist</tense>
            <voice>middle</voice>
            <stemtype>emi_aor</stemtype>
          </infl>
        </entry>
      </cnt:rest>
    </oac:Body>
   ...
```

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment]
I think I did the matching rules for the verbs, back in the days!!!! I guess the 'a' of aor got lost somewhere....

**Comment by monzug** [comment]
ποιῶ  and  ποιοῦμεν :   we show both tables now.
δύῃ : we show 3 tables now
ἔθετο  : we show also the τίθημι: Aorist System Middle table

for  πλεῖ  :     now we do have 3 tables -> Present System Active of Contract Verbs in -έω (monosyllabic stems)  -  Present System Middle-Passive of Contract Verbs in -έω (monosyllabic stem)  -  Present System Active of Contract Verbs in -έω
Looking at the endings, I would say that the best matches are for Present System Active of Contract Verbs in -έω (monosyllabic stems)  and   Present System Active of Contract Verbs in -έω
but we have a second person sing pres. ind. MP in the morphology. soooo, two questions here: 
1) should we show all 3 tables for  πλεῖ  ?
2) is there a way for me to check the morphology as I am not sure if  πλεῖ  should also be Present System Middle-Passive of Contract Verbs in -έω (monosyllabic stem)

**Comment by balmas** [comment]
This is the parser output for πλεῖ (accessible at http://morph.alpheios.net/api/v1/analysis/word?word=πλεῖ&lang=grc&engine=morpheusgrc)

```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <oac:Annotation xmlns:oac="http://www.openannotation.org/ns/" rdf:about="urn:TuftsMorphologyService:πλεῖ:morpheusgrc">
    <dcterms:creator xmlns:dcterms="http://purl.org/dc/terms/">
      <foaf:Agent xmlns:foaf="http://xmlns.com/foaf/0.1/" rdf:about="org.perseus:tools:morpheus.v1"/>
    </dcterms:creator>
    <dcterms:created xmlns:dcterms="http://purl.org/dc/terms/">2018-10-24T19:27:43.758412</dcterms:created>
    <dc:rights xmlns:dc="http://purl.org/dc/elements/1.1/">Morphology provided by Morpheus from the Perseus Digital Library at Tufts University.</dc:rights>
    <oac:hasTarget>
      <rdf:Description rdf:about="urn:word:πλεῖ"/>
    </oac:hasTarget>
    <dc:title xmlns:dc="http://purl.org/dc/elements/1.1/"/>
    <oac:hasBody rdf:resource="urn:uuid:idm140190918051432"/>
    <oac:Body rdf:about="urn:uuid:idm140190918051432">
      <rdf:type rdf:resource="cnt:ContentAsXML"/>
      <cnt:rest xmlns:cnt="http://www.w3.org/2008/content#">
        <entry uri="">
          <dict>
            <hdwd xml:lang="grc">πλέω</hdwd>
            <pofs order="1">verb</pofs>
          </dict>
          <infl>
            <term xml:lang="grc">
              <stem>πλ</stem>
              <suff>εῖ</suff>
            </term>
            <pofs order="1">verb</pofs>
            <mood>indicative</mood>
            <num>singular</num>
            <pers>2nd</pers>
            <tense>present</tense>
            <voice>mediopassive</voice>
            <dial>Attic epic Doric Ionic</dial>
            <stemtype>evw_pr</stemtype>
            <derivtype>ev_stem</derivtype>
            <morph>contr</morph>
          </infl>
          <infl>
            <term xml:lang="grc">
              <stem>πλ</stem>
              <suff>ει</suff>
            </term>
            <pofs order="1">verb</pofs>
            <mood>imperative</mood>
            <num>singular</num>
            <pers>2nd</pers>
            <tense>present</tense>
            <voice>active</voice>
            <dial>Attic epic</dial>
            <stemtype>evw_pr</stemtype>
            <derivtype>ev_stem</derivtype>
            <morph>contr</morph>
          </infl>
          <infl>
            <term xml:lang="grc">
              <stem>πλ</stem>
              <suff>εῖ</suff>
            </term>
            <pofs order="1">verb</pofs>
            <mood>indicative</mood>
            <num>singular</num>
            <pers>3rd</pers>
            <tense>present</tense>
            <voice>active</voice>
            <dial>Attic epic Doric Ionic</dial>
            <stemtype>evw_pr</stemtype>
            <derivtype>ev_stem</derivtype>
            <morph>contr</morph>
          </infl>
          <infl>
            <term xml:lang="grc">
              <stem>πλ</stem>
              <suff>ει</suff>
            </term>
            <pofs order="1">verb</pofs>
            <mood>imperative</mood>
            <num>singular</num>
            <pers>2nd</pers>
            <tense>present</tense>
            <voice>active</voice>
            <dial>Attic epic</dial>
            <stemtype>ew_pr</stemtype>
            <derivtype>ev_stem</derivtype>
            <morph>contr</morph>
          </infl>
          <infl>
            <term xml:lang="grc">
              <stem>πλ</stem>
              <suff>ει</suff>
            </term>
            <pofs order="1">verb</pofs>
            <mood>indicative</mood>
            <num>singular</num>
            <pers>3rd</pers>
            <tense>imperfect</tense>
            <voice>active</voice>
            <dial>Attic epic</dial>
            <stemtype>evw_pr</stemtype>
            <derivtype>ev_stem</derivtype>
            <morph>contr unaugmented</morph>
          </infl>
        </entry>
      </cnt:rest>
    </oac:Body>
  </oac:Annotation>
</rdf:RDF>
```

**Comment by balmas** [comment]
it does report mediopassive as one of the possible forms, so I would say that all 3 tables are justifiable, assuming the parser output is correct. What do you think?

**Comment by monzug** [comment]
Argh, I wish I had an answer. it does not look right to me but I am not a Greek expert... I looked at online grammars. I can see the exact match on the imperative and the indicative, but not in the middle passive. Bridget, what do we do here? we have to question the parser output. not sure we want to go down that road....

**Comment by monzug** [comment]
yes!
