### ISSUE TITLE
Second Aorist of βαίνω, γιγνώσκω, ἁλίσκομαι, δύω title should be moved

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#212]
I believe that the Second Aorist of βαίνω, γιγνώσκω, ἁλίσκομαι, δύω title should be moved below the Present System Middle-Passive of Contract Verbs in -όω section in the web browser.
it looks like the Second Aorist of βαίνω, γιγνώσκω, ἁλίσκομαι, δύω title should go in the Others section where we have the following verbs:
βαίνω: Aorist System Active [+]
γιγνώσκω: Aorist System Active [+]
ἁλίσκομαι: Aorist System [+]
δύω: Aorist System Active [+]

**Comment by monzug** [comment]
an other one that I am not sure about: should Athematic Perfects ἵστημι (in addition to forms from ἕστηκα)  be under the Present System of Contract Verbs (-εω, -αω, -οω) title?

**Comment by balmas** [comment]
Are we out of order with the original source? http://ucbclassics.dreamhosters.com/ancgreek/paradigmsU/paradigms_U.html

**Comment by monzug** [comment]
comparing the index of the Greek tables (not the content, yet) in the two sites. 
1) there is no such a title as Second Aorist of βαίνω, γιγνώσκω, ἁλίσκομαι, δύω - I would remove it unless we want to use as a title in the Others section as suggested above
2) we should add a new section for Athematic Perfects.
in these section, we should have 3 tables:
ἵστημι (in addition to forms from ἕστηκα)  - we do not have the Infinitive and Participle
θνῄσκω (in addition to forms from τέθνηκα)  - this one is missing from our tables
δέδια (in addition to forms from δέδοικα) - this one is missing from our tables

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment]
So happy to see this update to the Greek verb list. Approved!

**Comment by monzug** [comment]
see also issue #222
