### ISSUE TITLE
we should add the link to verb participle

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#213]
the Future Perfect Indicative, Infinitive, Participle table should have an active link to Participles in -μενος, -μένη, -μενον (all middle-passive and middle except perfect) as in http://ucbclassics.dreamhosters.com/ancgreek/paradigmsU/paradigms_U.html

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist
