### ISSUE TITLE
Some endings for the imperfect indicative don't match the paradigm table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#214]
I did compare the Present System Middle-Passive of Contract Verbs in -έω with the same table from http://ucbclassics.dreamhosters.com/ancgreek/paradigmsU/paradigms_U.html.
in the imperfect indicative, the first, second and third person singular ἐποίουν , ἐποίεις ,  ἐποίει 
should be ἐποιούμην (1st person singular), ἐποιοῦ  (2nd person singular),  ἐποιεῖτο (3rd person singular).
I did double-check the ending for the first person singular with endings from other online grammars and it seems consistent. for the other two endings, I could not find a definitive answer so I am assuming that the paradigm table is correct and we should change all three of them.

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment]
Thanks for fixing this.
