### ISSUE TITLE
Next view after a collapse table does not show the full table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#215]
lookup for χρῆται - the Greek verb has matches in several tables. from Present System Middle-Passive of Contract Verbs in -άω (with η contraction) view, click on [-] and then select Present System Active of Contract Verbs in -άω  from drop-down. the next view is with the infinitive and participle tables open. if I click on the [+], the Present System Active of Contract Verbs in -άω table is open with no infinitive and participle. if I change table from drop-down, then the full regular tables are displayed.
![screenshot_2018-10-10 homerus-odyssea i](https://user-images.githubusercontent.com/41396793/46749136-2185d080-cc83-11e8-9506-51380afc1f87.png)
![screenshot_2018-10-10 homerus-odyssea i 1](https://user-images.githubusercontent.com/41396793/46749166-2cd8fc00-cc83-11e8-8d70-bfb570ee3507.png)

**Comment by balmas** [comment]
not too surprised by this. handling that state was very hacky.

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/v2.0.3.2/dist

**Comment by monzug** [comment]
now it works fine. if a table is collapsed and I chose a new one from drop-down, I will need to click on the [+] to expand the table.
question on the tables that populate the drop-down. in the release build, we have 3 tables: 
Present System Middle-Passive of Contract Verbs in -άω (with η contraction)
Present System Active of Contract Verbs in -άω
Present System Middle-Passive of Contract Verbs in -άω 
in the latest build, we have 4 tables, the new one is the Present System Middle-Passive of Contract Verbs in -έω  which has two cells highlighted.
I am not sure if we should show the Present System Active of Contract Verbs in -άω  (this one has no matches) - looking at the morphology panel, they are all mp (no one is active)

**Comment by balmas** [comment]
> now it works fine. if a table is collapsed and I choose a new one from drop-down, I will need to click on the [+] to expand the table.
> question on the tables that populate the drop-down. in the release build, we have 3 tables:
> Present System Middle-Passive of Contract Verbs in -άω (with η contraction)
> Present System Active of Contract Verbs in -άω
> Present System Middle-Passive of Contract Verbs in -άω
> in the latest build, we have 4 tables, the new one is the Present System Middle-Passive of Contract Verbs in -έω which has two cells highlighted.
> I am not sure if we should show the Present System Active of Contract Verbs in -άω (this one has no matches) - looking at the morphology panel, they are all mp (no one is active)

I have moved this to #231  
Can we close this issue?
