### ISSUE TITLE
big limitation in the Greek matching "algorithm"

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#216]
there is a big limitation with the matching "algorithm" due to the morphology. 
at the end we do show only few of the tables that we have in the system.  I think the match is based also on the morphology and we don't always have all the information for a better match.
e.g.  ἱῆται  from verb ἵημι: Present System Middle-Passive table
ἱῆται is pres. sub. md.  and pres. ind. mp.  We do match with the Present System Middle-Passive of Contract Verbs in -έω table not the ἵημι table.
I don't know if there is a way to fix this.

**Comment by balmas** [comment]
we never did really good testing of the rules applied for matches into the greek paradigm tables before.

**Comment by monzug** [comment]
it works well, but there is room for improvement

**Comment by monzug** [comment]
many but I need to go back to the Greek tables or my notes. I chose the
'wrong' example....

**Comment by monzug** [comment]
still looking, instead I found φῶ that we say it's a verb in morphology but
then we do not have the inflect button.

**Comment by monzug** [comment]
5)  δύῃ is from δύω Aorist system active  - we have two verbs:  ω-Verbs: Present System Middle-Passive  and  ω-Verbs: Present System Active

**Comment by monzug** [comment]
7. I have a note for  ἔθετο  - we only show ω-Verbs: Present System Middle-Passive table but it's also aorist ind. mid.

**Comment by balmas** [comment]
> still looking, instead I found φῶ that we say it's a verb in morphology but then we do not have the inflect button.

This one is because morpheus apparently doesn't report tense for the forms in the present tense for this table. We need to add a rule that allows matching into this table if tense isn't present.

**Comment by balmas** [comment]
>χρῴη it's Present System Active of Contract Verbs in -άω (with η contraction) but it shows the
Present System Active of Contract Verbs in -άω table

This one is tough. The rules expect the parser to identify the stemtype of verbs in that table (Present System Active of Contract Verbs in -άω (with η contraction) ) to be ajw_pr and the verbs in (Present System Active of Contract Verbs in -άω) as aw_pr. And for most of the forms it does, but for some reason for the optative forms in the singular and plural it only reporting aw_pr and not ajw_pr.  Maybe we need to add an extra layer of matching which allows us to also match on the exact form regardless of the rules.

**Comment by balmas** [comment]
>ἐλῴη it's Future System (Active) with contraction in -άω but it shows the Future System (Active and Middle) with contraction in -έω table

This one actually looks like it's doing the right thing to me. There are 2 possible inflections reported for this, one is in the fut opt active and the other is pres. opt. active.  (the morph display doesn't tell you that the latter is a different dialect, epic vs Attic, it should see alpheios-project/components#262

**Comment by balmas** [comment]
>δέδια it's Athematic Perfect δέδια (in addition to forms from δέδοικα) but it shows the Perfect Active System table
There are 2 problems here: 
 - 1 we are missing some of the athematic perfect tables -- see #222 
 - 2 the parser doesn't actually report δέδια as athematic - we expect that to be indicated via the perf2_act stemtype but it just says perf_act for this verb. Once #222 is addressed this could be fixed by #221

**Comment by balmas** [comment]
>πλεῖ it's middle passive and also Present System Active of Contract Verbs in -έω (monosyllabic stems) but it only shows the middle passive table

This is fixed by #210

**Comment by balmas** [comment]
>δύῃ is from δύω Aorist system active - we have two verbs: ω-Verbs: Present System Middle-Passive and ω-Verbs: Present System Active
This is fixed by #210

**Comment by balmas** [comment]
>εἰδείη is from οἶδα: Perfect System - it goes to Perfect Active System
I think we need to add a rule on lemma for that table. #223

**Comment by monzug** [comment]
the only issue left is the following:
χρῴη it's Present System Active of Contract Verbs in -άω (with η contraction) but it shows the
Present System Active of Contract Verbs in -άω table

This one is tough. The rules expect the parser to identify the stemtype of verbs in that table (Present System Active of Contract Verbs in -άω (with η contraction) ) to be ajw_pr and the verbs in (Present System Active of Contract Verbs in -άω) as aw_pr. And for most of the forms it does, but for some reason for the optative forms in the singular and plural it only reporting aw_pr and not ajw_pr. Maybe we need to add an extra layer of matching which allows us to also match on the exact form regardless of the rules.

Question
would be easier for these optative forms to show both tables? the endings are the same

**Comment by monzug** [comment]
to retest when #289 will be fixed
