### ISSUE TITLE
δύναμαι (ἐπίσταμαι): Present System Middle-Passive

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#218]
δύναμαι (ἐπίσταμαι): Present System Middle-Passive table is the result of merging two verbs: δύναμαι and ἐπίσταμαι. unfortunately the merge didn't go so well. we need to review the table to add some missing endings and fix some mistakes (specially in the imperative column). an other solution would be to create a separate table for  ἐπίσταμαι as  in the paradigm reference table.

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment]
Now the table matches the one from http://ucbclassics.dreamhosters.com/ancgreek/paradigmsU/paradigms_U.html  except for the title:
δύναμαι and ἐπίσταμαι: Present System Middle-Passive.   we only have δύναμαι: Present System Middle-Passive table. is this intentional?

**Comment by balmas** [comment]
I split it into 2 tables, but I just realized I forgot to add the browser entry for the second table, the one for ἐπίσταμαι . Will do that.

**Comment by monzug** [comment]
hahaha easy to get 'lost' with the Greek verb.

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/v2.0.3.2/dist

**Comment by monzug** [comment]
the new table is listed in the Greek verb browser and the matching is also working.
