### ISSUE TITLE
typo in rules for paradigm table 31 (τίθημι aorist system milddle)

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#219]
> moved from #216

ἔθετο is yet a different issue :-) we seem to be missing all of the τίθημι aorist system middle matches due to a typo in the rules (looking for stemtype emi_or instead of emi_aor)

_Originally posted by @balmas in https://github.com/alpheios-project/inflection-tables/issue_comments#issuecomment-431111531_

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment]
ἔθετο does have a match in the τίθημι: Aorist System Middle
