### ISSUE TITLE
Reduce whitespace in inflection tables

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#22]
@abrasax would like us to reduce the whitespace in the inflection tables so that the presentation is more compact.

<img width="1273" alt="screen shot 2018-01-31 at 4 26 38 pm" src="https://user-images.githubusercontent.com/644870/35655068-07436718-06be-11e8-900c-71a107a3766d.png">

**Comment by kirlat** [comment]
Please see 37bf7304b0531a86ef9c65ec6939e0fc4ea0b0bd, alpheios-project/webextension@58d6237de12ee182c8a64d84d4fd3d56ecb26243 addresses that. Let me know if it's too much or too little.

**Comment by abrasax** [comment]
Well, there is no correct size. It has to dynamically adjust to how much
text there is in the popup.

**Comment by kirlat** [comment]
Further reduced spacing with 20997c4067f47be8d77f2dd7ad2cee971b54a802, alpheios-project/webextension@920cffa3eb03a8cf4b990ec7022713ea1f93d6c2.

**Comment by balmas** [comment]
@abrasax how is this?
![verb](https://user-images.githubusercontent.com/644870/35703735-25ae5ab6-076b-11e8-96e4-d8f3d5ad5763.png)
![noun](https://user-images.githubusercontent.com/644870/35703736-25bc45d6-076b-11e8-9cda-693e33207ec5.png)

**Comment by balmas** [comment]
done
