### ISSUE TITLE
match into verbpdgm48 for ath_primary with no tense

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#220]
morpheus doesn't report tense for φῶ and other forms of ath_primary verbs in the present tense. This is verb paradigm table #48 and the rules currently require tense (present or imperfect).  We need to add a rule that allows matching into this table if tense isn't present.

_Originally posted by @balmas in https://github.com/alpheios-project/inflection-tables/issue_comments#issuecomment-431116112_

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment]
1) φῶ  and  φῇς  and  φῆτε : the cells are not highlighted in the φημί: Present System table

2) the optative  φαίη  and  φαῖμεν and  φαῖεν  go to the ἵστημι: Present System Active

3) φατω (imperative) : lexical query produced not results

**Comment by balmas** [comment]
> * φῶ  and  φῇς  and  φῆτε : the cells are not highlighted in the φημί: Present System table
> * the optative  φαίη  and  φαῖμεν and  φαῖεν  go to the ἵστημι: Present System Active
> * φατω (imperative) : lexical query produced not results

Fixed 1 and 2. 3 is a bug in the parser, noted as alpheios-project/morphsvc#17 but may not get fixed anytime soon.

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/v2.0.3.2/dist

**Comment by monzug** [comment]
fixed the following:
φῶ and φῇς and φῆτε : the cells are not highlighted in the φημί: Present System table
the optative φαίη and φαῖμεν and φαῖεν go to the ἵστημι: Present System Active
