### ISSUE TITLE
Athematic Perfects - missing some tables

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#222]
The source data at http://ucbclassics.dreamhosters.com/ancgreek/paradigmsU/paradigmtables4BOM.html#verbpdgm17 has several verbs besides ἵστημι for paradigm17 but we only seem to have captured the first

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment]
now we have two additional tables:
Athematic Perfects - θνῄσκω (in addition to forms from τέθνηκα) 
Athematic Perfects - δέδια (in addition to forms from δέδοικα) 
this was reported in issue #212
