### ISSUE TITLE
Add rule to match on lemma οἶδα for table 53 (οἶδα: Perfect System)

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#223]
This appears to be a lemma-specific table, and we don't have a rule that matches on that lemma. 
This may be way we miss e.g. on εἰδείη (see #216)

**Comment by balmas** [comment]
I'm not sure though if any other verbs should  match into this table. The existing rules include:

- match on stemtype=perf_act, voice=active, tense=pluperfect
- match on stemtype=ath_primary, tense=perfect

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment]
εἰδείη (and tested for many others) goes now to οἶδα: Perfect System
