### ISSUE TITLE
is tense correct for optative column in οἶδα: Perfect System (verbpdgm53)

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#224]
@monzug not sure if you can answer this but I'm confused about something with the οἶδα: Perfect System table.  The parser reports the tense as 'perfect' for the forms in the optative column, but that column says its present tense. Do you know which is correct?

**Comment by monzug** [comment]
checked two grammars and one says present (see 1 below) and the other (see
2 below) says perfect. I think it's perfect

1) opt. present  active (οἶδα)
εἰδείην
εἰδείης
εἰδείη
εἰδεῖμεν
εἰδεῖτε
εἰδεῖεν

2) οἶδα
 Optative Mood
Perfect Active
Singular εἰδείην εἰδείης εἰδείη
Dual εἰδεῖτον (εἰδείητον) εἰδείτην (εἰδειήτην)
Plural εἰδεῖμεν (εἰδείημεν) εἰδεῖτε (εἰδείητε) εἰδεῖεν (εἰδείησαν)

**Comment by balmas** [comment]
@monzug is it possible it's both?

**Comment by monzug** [comment]
everything it's possible with Greek and related grammars... I have seen it
all.
let me check more online grammars. the second grammar looks like a reliable
source (e-edu.nbu.bg)

**Comment by monzug** [comment]
this is from the university of Chicago - I think we could be safe to call
it just optative (refer to the perfect system)

**Comment by balmas** [comment]
ok. I will remove the tense speicifier from it then. Thank you!

**Comment by monzug** [comment]
yes!

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment]
so glad that we opted for the easy solution. it did bother me when I first noticed it and could not come up with a solution.
