### ISSUE TITLE
verbs do not match the new table Athematic Perfects - δέδια (in addition to forms from δέδοικα)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#227]
e.g. δέδια  and  δεδίῃ   and  δεδίητον  and δεδίητε go to the Perfect Active System table
e.g. δέδιτον  (dual)  and  ἐδεδίειμεν  lexical query produced no results
e.g. δέδιμεν - it opens the correct table but the ending is not highlighted
e.g. δέδιτε  - it does highlight the wrong cell: imperative, 2nd person Plural  
e.g. ἐδεδίειν  - it goes to two tables, the οἶδα: Perfect System  and  Pluperfect Middle-Passive Indicative

**Comment by balmas** [comment]
> e.g. δέδια and δεδίῃ and δεδίητον and δεδίητε go to the Perfect Active System table
> e.g. ἐδεδίειν - it goes to two tables, the οἶδα: Perfect System and Pluperfect Middle-Passive Indicative

These I was able to fix with rule updates

**Comment by balmas** [comment]
> e.g. δέδιτον (dual) and ἐδεδίειμεν lexical query produced no results
These are parser failures, not easy to fix, entered as alpheios-project/morphsvc#18

**Comment by balmas** [comment]
>e.g. δέδιμεν - it opens the correct table but the ending is not highlighted
e.g. δέδιτε - it does highlight the wrong cell: imperative, 2nd person Plural

These are mismatches in the parser output and our paradigm data. Assuming the paradigm table is correct, these are also reported in https://github.com/alpheios-project/morphsvc/issues/18

**Comment by monzug** [comment]
δέδιτε   I confirm that it's perfect indicative 2nd person Plural  may be
the paradigm table is based on the same source I have checked: a guide to
greek verbs by sophocles....)

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/v2.0.3.2/dist

**Comment by monzug** [comment]
the following have been fixed:
e.g. δέδια and δεδίῃ and δεδίητον and δεδίητε go to the Perfect Active System table
e.g. ἐδεδίειν - it goes to two tables, the οἶδα: Perfect System and Pluperfect Middle-Passive Indicative

**Comment by monzug** [comment]
Bridget,
I did also close this one. not sure if I should do it. please advice. Thanks

**Comment by balmas** [comment]
yep, thanks!
