### ISSUE TITLE
verb has not cell highlighted in the Future Perfect Indicative, Infinitive, Participle

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#228]
verb τεθνήξετον  (dual)  and  τεθνήξω   and  λελυσόμεθα   do not have the cells highlighted in the Future Perfect Indicative, Infinitive, Participle table
see issue #213

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/v2.0.3.2/dist

**Comment by monzug** [comment]
they do now. Thanks
