### ISSUE TITLE
χρῆται - don't show present system active table

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#231]
question on the tables that populate the drop-down. in the release build, we have 3 tables: 
Present System Middle-Passive of Contract Verbs in -άω (with η contraction)
Present System Active of Contract Verbs in -άω
Present System Middle-Passive of Contract Verbs in -άω 
in the latest build, we have 4 tables, the new one is the Present System Middle-Passive of Contract Verbs in -έω  which has two cells highlighted.
I am not sure if we should show the Present System Active of Contract Verbs in -άω  (this one has no matches) - looking at the morphology panel, they are all mp (no one is active)

_Originally posted by @monzug in https://github.com/alpheios-project/inflection-tables/issues/215#issuecomment-433716312_

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.3/dist

**Comment by balmas** [comment]
Please also retest matching for Present System Active of Contract Verbs in -άω because I reduced the priority of a match rule for that table to fix this.

**Comment by monzug** [comment]
works great also checked all matches in the Present System Active of Contract Verbs in -άω  table
