### ISSUE TITLE
ἠγγέλμεθα: participle is also highlighted but it shouldn't

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#233]
ἠγγέλμεθα is a greek verb shown in two tables: Pluperfect Middle-Passive Indicative and Perfect System Middle-Passive: indicative, infinitive, participle
in the latest table, the participle is also highlighted but it shouldn't.

<pofs order="1">verb</pofs><mood>indicative</mood><num>plural</num><pers>1st</pers><tense>pluperfect</tense><voice>mediopassive</voice><dial>Attic epic Doric Ionic Aeolic</dial><stemtype>perfp_l</stemtype><derivtype>ellw</derivtype><morph>redupl</morph></infl><infl><term xml:lang="grc"><stem>ἠγγε</stem><suff>λμεθα</suff></term><pofs order="1">verb</pofs><mood>indicative</mood><num>plural</num><pers>1st</pers><tense>perfect</tense><voice>mediopassive</voice><dial>Attic epic Doric Ionic Aeolic</dial><stemtype>perfp_l</stemtype><derivtype>ellw</derivtype><morph>redupl</morph></infl>

![perfect-system-mp](https://user-images.githubusercontent.com/41396793/47788989-b2335780-dce9-11e8-9dcb-686e1ab1b920.JPG)

**Comment by monzug** [comment]
also  ὁρῶσῐ  has the participle highlighted in the Present System Active of Contract Verbs in -άω  table

**Comment by balmas** [comment]
this can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.4/dist
hopefully the last item for the patch release...

**Comment by balmas** [comment]
this apparently wasn't fully fixed - as @monzug reports in alpheios-project/components#846, there are still some rows in this table which don't have part of speech specified.

**Comment by balmas** [comment]
should be fixed in qa-3.0.3.88/components 1.4.6
