### ISSUE TITLE
ἐλῴη  :  participle is highlighted but it shouldn't

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#237]
ἐλῴη  is  verb in the Future System (Active and Middle) with contraction in -έω  table and in the Present System Active of Contract Verbs in -άω 

for some reason, the active participle is highlighted in the Future System (Active and Middle) with contraction in -έω table and it shouldn't because it's not verb participle accordingly to morphology panel.

similar to issue #233

**Comment by balmas** [comment]
qa3.0.3.87/components 1.4.5

**Comment by monzug** [comment]
yes.
