### ISSUE TITLE
few issues with Aeneadum, proper name

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#240]
from http://www.thelatinlibrary.com/lucretius/lucretius1.shtml, double click on Aeneadum  - it gives lexical query produced no results.
in Whitaker is  a name 
Aeneadum             N      0 0 X   X X                 
Assume this is capitalized proper name/abbr, under MODE IGNORE_UNKNOWN_NAME

lookup for aeneadum (lower case),  we don't show the same lemmas as Whitaker. we show the lemma adum but not aenum, aeni  N  - see screenshot
in Whitaker, aeneadum  
Two words            
May be 2 words combined (aene+adum) If not obvious, probably incorrect
aen.e                N      2 2 NOM P N                 
aen.e                N      2 2 ACC P N                 
aenum, aeni  N  N   [XXXCO]  
vessel made of copper/bronze; brazen vessel; kettle, pot, cauldron;
aen.e                ADJ    1 1 VOC S M POS             
aenus, aena, aenum  ADJ   [XXXCO]  
copper, of copper (alloy); bronze, made of bronze, bronze-colored; brazen;
e                    SUFFIX                             
-ly; -ily;  Converting ADJ to ADV
aen.e                ADV    POS                         
aenus, aena, aenum  ADJ   [XXXCO]  
copper, of copper (alloy); bronze, made of bronze, bronze-colored; brazen;
*
![screen shot 2018-11-11 at 6 17 47 pm](https://user-images.githubusercontent.com/41396793/48316040-49e45000-e5de-11e8-925a-c6aa7aa4ace7.png)

Also, I think we can combine the two adjectives as they have the same meaning.

**Comment by balmas** [comment]
Ok, I entered 2 issues for this. The proper-name we might be able to address easily with a change to the morph-client (that's alpheios-project/morph-client#31) but the errors with aeneadum require a change to the whitaker parser code, which isn't likely to happen.

**Comment by monzug** [comment]
Thanks.
