### ISSUE TITLE
Can we remove the supine sentence in the verb browser for all the irregular verbs that do not have supine

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#252]
All the compounds of sum such as adsum absum etc do not have the supine. it would be nicer if we do not display the table hasn't been implemented yet sentence for these verbs. Will provide a full list of verbs with no supine.

**Comment by abrasax** [comment]
I would agree

**Comment by monzug** [comment]
@balmas, do we postpone or could it be done?

**Comment by balmas** [comment]
I think we have to postpone unfortunately :-(. We can put it in an incremental.

**Comment by monzug** [comment]
yes, pls!

**Comment by monzug** [comment]
so happy to see this one!!!! Thanks

**Comment by balmas** [comment]
qa-3.0.1.72

**Comment by monzug** [comment]
ok, the sentence is gone from the inflection browser but the irregular verbs with a supine such as fero, adeo etc, do not show the inflection table any longer. if I look up for latum or venitu, there is no inflection icon in morphology pop-up. we do display the supine table for regular verbs such as actum.

**Comment by balmas** [comment]
ah, nice catch. I had tested fero but not latum. Missed a spot that needs to be changed. Code is throwing an error

alpheios-inflection-tables.min.js:2 Cannot build inflection tables: TypeError: this.constructor.linkedViewConstructors is not a function or its return value is not iterable

**Comment by monzug** [comment]
worse scenario we can reverse to previous build and we keep the ugly
message...

**Comment by balmas** [comment]
no it should be an easy fix. it was just an oversight.

**Comment by balmas** [comment]
qa 3.0.1.74/components 1.2.50

**Comment by monzug** [comment]
looks good.
