### ISSUE TITLE
fix future perfect of eo

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#262]
ierint not ierunt (user reported)

**Comment by monzug** [comment]
so glad we got this feed-back!!!! thank to this user.

add also iverim and ivissem to the subjunctive perfect and pluperfect

**Comment by monzug** [comment]
to do next in the irregular table: add all missing form for eo + odeo table + remove accent to desum

**Comment by balmas** [comment]
this will be in the next build (3.0.0.30)

**Comment by monzug** [comment]
I will wait for this fix and then will start digging into the left-over...

**Comment by balmas** [comment]
in webextension qa-3.0.0.30 and texts-test (embed-lib 1.0.0.6)
(https://github.com/alpheios-project/webextension/tree/qa-3.0.0.30/dist and Dropbox)

**Comment by monzug** [comment]
Thanks!!!!
