### ISSUE TITLE
desum doesn't match dēsum inflection data

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#276]
When lookup up desum (or even dēsum) we don't get the inflection table for dēsum . I think this is because we aren't doing a model-specific compare of the word form everywhere we need to be.

_Originally posted by @balmas in https://github.com/alpheios-project/inflection-tables/issues/250#issuecomment-534598699_

**Comment by balmas** [comment]
I believe the changes necessary for this include the following:

In LatinLanguageDataset, everywhere we compare a word to an inflection value we need to use modelCompareWord.

E.g.

```const lemma = this.irregularLemmas.get(pofs).find(item => item.word ===inflection[Feature.types.word].value)```

```this.irregularLemmas.get(pofs).some(item => item.word === inflection[Feature.types.word].value)```

```return this.irregularLemmas.get(pofs).some(item => item.word === inflection[Feature.types.word].value)```

each need to be changed

In addition, we need to implement an override to `morpheme.matchingValues` in the `Form` derived class, to have it do modelCompareLanguage on features of type word and form.

**Comment by monzug** [comment]
confirm that it's still not working
![defuturus](https://user-images.githubusercontent.com/41396793/68949418-faec7000-0787-11ea-8114-fd0b752d57e6.JPG)

**Comment by irina060981** [comment]
Going through the closed issues - I checked this - and both
desum and defuturus
returns unplemented Verb irregular
![image](https://user-images.githubusercontent.com/12377640/70602421-1d1ac600-1c40-11ea-9c5e-16cf9fbc6254.png)

**Comment by monzug** [comment]
Irina, the fix for desum should be included in the next build. Hopefully it will work.
