### ISSUE TITLE
need to review the noun inflection table for the LOCATIVE case

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#282]
at first glance, I found few endings that need to be updated
4th decl sing: ending should be  ī  and not  u  and apparently not plural, no endings for 5th decl and also the second decl endings need to be reviewed.

it is still used in names of cities and islands in the 1st and 2nd decl and few other words such as humi, domi and ruri

I decl:
singular Rōmae
plural Athenīs
II decl:
singular Cyprī 
plural Delphīs 
III decl: 
singular rūrī 
plural is not used
IV decl:
singular domī 
plural is not used

**Comment by monzug** [comment]
in the inflection tables, I would change the locative sing 2nd decl from o to ī
remove the plural locative in 3rd and 4th decl.
change the locative sing 4th decl from u to ī  (such as domī)

**Comment by balmas** [comment]
qa-3.0.1.76/components 1.3.1

**Comment by monzug** [comment]
tested in Safari App Extension 3.0.1.76
Alpheios Components 1.3.1
