### ISSUE TITLE
extra forms in the greek personal pronoun table

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#29]
Need to investigate why extra forms are showing up in the greek Personal Pronoun table. V1 vs V2 screenshots attached.
![screenshot from 2018-03-29 15-52-16](https://user-images.githubusercontent.com/644870/38110327-37250cca-3369-11e8-9ddf-434da53043d4.png)
![screenshot from 2018-03-29 15-52-09](https://user-images.githubusercontent.com/644870/38110328-37303aa0-3369-11e8-8ee4-1e0c8d928717.png)

**Comment by balmas** [comment]
Notes on debugging:

I'm not positive, but I think what's happening here is that forms for the 2 classes of inflections are being merged. 

The word ἡμῶν matches 2 classes of inflection data - personal pronoun and reflexive pronoun
the personal pronoun view gets the same number of forms (129) in its data set as the reflexive view does. 

The extra values in the personal view (e.g in the cell for 1st, plural, genitive) have gender in their features, but the personal class data in the source data file does not include gender.

So either the problem is that the data for both classes should not be passed to the View, or the View itself is not filtering on class properly.

**Comment by balmas** [comment]
I think the issue is in View.getMorphemes. At this point, inflectionData.pos.get('pronoun') returns the pronoun data for all the matching classes of pronouns and the data isn't further filtered by class after this point.

**Comment by kirlat** [comment]
Did my testing and found no issues, please verify that it is working correctly in test cases you were using. Thanks!
