### ISSUE TITLE
view-set constructor fails if one invalid inflection

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#293]
if I double click   οἰστροδόνου     from    Safari, Alpheios Components 1.4.7
https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg001.alpheios-text-grc1/passage/1-30
the output is different from the lookup - see screenshots
![Screen Shot 2019-11-08 at 3 48 18 PM](https://user-images.githubusercontent.com/41396793/68485409-8a9d9600-023f-11ea-9762-256da1dea303.png)
![Screen Shot 2019-11-08 at 3 46 30 PM](https://user-images.githubusercontent.com/41396793/68485410-8b362c80-023f-11ea-916b-4dbe153b9d38.png)

I didn't see anything weird in morpheus. also one has the inflection icon only and the other has only the diagram icon.

**Comment by monzug** [comment]
same in Chrome

**Comment by balmas** [comment]
well the difference is because the text is treebanked, and the treebank data identifies the lemma as οτηερ and does not specify any morphological characteristics.  This may be an error in the treebank data, I'm not sure. It is odd that we don't get the inflection tables for the other possibilities even though we show them though. I think that might be a bug.

**Comment by balmas** [comment]
the lack of a part of speech in the treebank data is causing the view-set constructor to fail in the following code:

```
 static create (homonym) {
    let viewSet
    try {
      const Constructor = this.getConstructor(homonym.languageID)
      viewSet = new Constructor(homonym)
    } catch (e) {
      console.error(`Cannot build inflection tables: ${e}`)
      // Create an empty ViewSet with no inflection data
      viewSet = new ViewSet()
    }
    return viewSet
  }
```

Since the homonym does contain some valid inflections, it should succeed and just ignore the invalid ones.

**Comment by balmas** [comment]
I will enter an issue in the treebank-data repository to report the invalid data for this word too.

**Comment by irina060981** [comment]
I found what should be fixed here.
Would be this way

![image](https://user-images.githubusercontent.com/12377640/72801539-69244600-3c95-11ea-88c0-59d50b87f1ad.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
webextension 3.0.6-qa.1 (components 1.6.0-dev)

**Comment by monzug** [comment]
to test this one I need the latest build of the tools. unfortunately when I type texts-test.alpheios.net it does automatically redirect to test.alpheios.net which run the release version, Alpheios Embedded Library 3.1.4.45
Alpheios Components 1.4.7
