### ISSUE TITLE
Missing the inflection icon for the subjunctive aorist mp

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#296]
Related to #289
we don't show the inflection icon for any of the form of the subjunctive Strong (2nd) Aorist System Middle such as ἀγάγηται
Looking at the rules.csv the culprit could be the middle vs mp (mediopassive)
the voice mediopassive is missing from rules.csv for the verbpdgm7	- we do only have the middle voice.
I think we should add an other line in verbpdgm7 like for verbpdgm2:
verbpdgm2	2	verb	w_stem	mediopassive
verbpdgm2	2	verb	w_stem	middle

**Comment by monzug** [comment]
missing inflection table icon for   ἀγάγηται

<infl><term xml:lang="grc"><stem>ἀγαγ</stem><suff>ηται</suff></term><pofs order="1">verb</pofs><mood>subjunctive</mood><num>singular</num><pers>3rd</pers><tense>aorist</tense><voice>mediopassive</voice><stemtype>aor2</stemtype><morph>redupl</morph></infl>

**Comment by monzug** [comment]
try again to link to issue #289

**Comment by monzug** [comment]
see related issue #318

**Comment by balmas** [comment]
yes, adding 

```verbpdgm7,1,verb,aor2,mediopassive,,,,,```

to the rules file would probably make sense here.

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
Irina, does it work in your test environment? Thanks for taking care of this issue.

**Comment by irina060981** [comment]
Monica, it looks like this

for `ἀγάγηται`

![image](https://user-images.githubusercontent.com/12377640/72775449-1bd6b300-3c5a-11ea-961e-ba487f8fedc4.png)

for `ἀγάγῃ`

![image](https://user-images.githubusercontent.com/12377640/72775495-4f194200-3c5a-11ea-908b-d9ec097965b3.png)

**Comment by monzug** [comment]
Fantastic. Thanks

**Comment by balmas** [comment]
webextension 3.0.6-qa.1 (components 1.6.0-dev)

**Comment by monzug** [comment]
tested in Chrome and FF  Alpheios Reading Tools 3.0.6.97
Alpheios Components 1.6.0-dev
