### ISSUE TITLE
paradigm matching plugin

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#299]
Add support for matching paradigm tables for greek nouns, adjectives and pronouns as well as verbs. 

Because we have already ending tables for those forms, we may have some additional work to do here to be able to display both, or prefer paradigm tables when they exist. 

We may implement this as plugin-module for paradigm matching which can be used with both the editing tool (#298) and the runtime components library.

_Originally posted by @balmas in https://github.com/alpheios-project/inflection-tables/issues/289#issuecomment-560537644_

**Comment by irina060981** [comment]
@balmas ,
I have started to work on adding noun paradigms and faced with the following problem:
I was not able to find any word from the table:
https://ucbclassics.dreamhosters.com/ancgreek/paradigmsU/paradigms_U.html
that had morphology result.

So I am not sure how to create a rule for the table?
Bridget, could you help me - how to solve this problem?

**Comment by irina060981** [comment]
@balmas , I believe that 
  - I am doing something wrong
  - Morpheius source doesn't have this type of words

Anyway I think that I need for the task
  - some ready rules for some tables - noun, adjectives, pronoun (I have no enough knowledge for creating them myself), or if it possible, some explanation, how I could create them myself
  - some words existed in Morpheius source for these tables to be able to test it

Without this information I don't know what to do further here.
@balmas , I hope to get your help here :)

**Comment by balmas** [comment]
@irina060981 I am not sure but I think this might have been caused by the load balancer I put in front of the morph service yesterday. I am getting reports from other users and Monica that something went wrong with that. I took the load balancer away while I try to figure out the cause of the failure. I think it's working now.

**Comment by balmas** [comment]
(In addition, you need to test the page outside of the iframe)

**Comment by balmas** [comment]
re the rules, I think to start we would match on either stem_type or lemma.  Not sure if we will be able to do more than that.

**Comment by irina060981** [comment]
great, now it is working (morphology, I mean)!

**Comment by balmas** [comment]
this is done.
