### ISSUE TITLE
Greek verbs: matching for verbs in verbpdgm5 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#300]
Related to  #289 
verbpadgm5 is the only table with the dialects specified in rules.csv
The matching for the verbs such as ἐλῴη in the Future System (Active) with contraction in -άω table is done on verbpadgm3 or verbpdgm4 tables and not on verbpdgm5.
Suggestion: we should try to remove the dialects and see if matching works.

**Comment by irina060981** [comment]
I have made this change for the test - here it is the result
![image](https://user-images.githubusercontent.com/12377640/72147323-fdff8780-33e9-11ea-8659-9579c65458cf.png)

![image](https://user-images.githubusercontent.com/12377640/72147332-035cd200-33ea-11ea-9546-6016f3e13672.png)

This way we get
verbpdgm5 (Future System (Active) with contraction in -άω)
verbpdgm22 (Present System Active of Contract Verbs in -άω)

@monzug and @balmas, should I do this change in production?

**Comment by monzug** [comment]
@irina060981, Hi Irina, did you update the rules.csv file by removing the dialects? it looks like it works.

**Comment by irina060981** [comment]
Yes, I did as you told in your message, so you could check the result, @monzug .

>Suggestion: we should try to remove the dialects and see if matching works.

**Comment by balmas** [comment]
But I'm not sure I did a build since then...

**Comment by irina060981** [comment]
Oh, it is only in my test environment! I didn't create a PR and merge it, @balmas!

**Comment by balmas** [comment]
ok, so yes please do a PR :-)

**Comment by monzug** [comment]
nope, but Irina tried in her environment and it worked as per screenshots.

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
@irina060981, I just noticed that there is a comment in rules.csv file. Apparently when you removed the dialects from the file, you forget a comma at the end of line 11. Could you please check the file? Thanks

**Comment by irina060981** [comment]
@monzug , great catch! Thank you! Will fix it.

**Comment by monzug** [comment]
it was github not me!

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
webextension 3.0.6-qa.1 (components 1.6.0-dev)

**Comment by monzug** [comment]
tested in Firefox  Alpheios Reading Tools 3.0.6.97
Alpheios Components 1.6.0-dev
