### ISSUE TITLE
ἐγράφην vs ἐβουλεύθην disambiguation (aorist vs 2nd aorist)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#301]
related to issue #289 
see  ἐγράφην      2nd aorist indicative from verbprdg10 table
the stemtype is aor2_pass  but also the cells for the indicative
stemtype  aor_pass  are highlighted and they shouldn't. 
same for   ἐβουλεύθην       indicative  from verbprdg10 table with stemtype aor_pass  but also the cells for the 2nd aorist indicative stemtype  aor2_pass  are highlighted and they shouldn't. 
looking at rules.csv we have
verbpdgm10	1	verb	aor_pass						
verbpdgm10	1	verb	aor2_pass
matchOrder is the same number so it does highlight both matches

**Comment by irina060981** [comment]
Here it is the same situation as https://github.com/alpheios-project/inflection-tables/issues/302

indicative and 2nd aorist indicative columns have no difference from properties perspective:
```
{
                "role": "data",
                "tense": "aorist",
                "voice": "passive",
                "number": "singular",
                "person": "1st",
                "mood": "indicative",
                "value": "ἐβουλεύθην"
            },
```
aorist passive singular 1st indicative
```
{
                "role": "data",
                "tense": "aorist",
                "voice": "passive",
                "number": "singular",
                "person": "1st",
                "mood": "indicative",
                "value": "ἐγράφην"
            }
```
aorist passive singular 1st indicative

@balmas and @monzug , so we should add some additional property here to distinguish them?

**Comment by balmas** [comment]
this one could probably be addressed by adding the stemtype to the cell data for the rows in the 2nd aorist indicative column.

**Comment by irina060981** [comment]
It would be then this way

![image](https://user-images.githubusercontent.com/12377640/72781628-79282f80-3c6d-11ea-833c-59ae99039512.png)

![image](https://user-images.githubusercontent.com/12377640/72781606-6c0b4080-3c6d-11ea-847b-65bf188d3d5f.png)

![image](https://user-images.githubusercontent.com/12377640/72781645-85ac8800-3c6d-11ea-86b7-c86f06b1bce3.png)

![image](https://user-images.githubusercontent.com/12377640/72781665-90ffb380-3c6d-11ea-83ad-f379d3c79e8c.png)

**Comment by monzug** [comment]
fantastic. looks like it works!

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
webextension 3.0.6-qa.1 (components 1.6.0-dev)

**Comment by monzug** [comment]
tesed in Chrome Alpheios Reading Tools 3.0.6.97
Alpheios Components 1.6.0-dev
works beautifully. thanks
