### ISSUE TITLE
missing stemtype in verbpdgm12 and verbpdgm15 tables, so all cells are highighted

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#303]
related to issue #289 
lookup for  λέλυμαι  it will highlight all the cells of the 1st person indicative in the Perfect System Middle-Passive: indicative, infinitive, participle  verbpadgm12 table.
stemtype field is empty in rules.csv so it's not used but
λέλυμαι    stemtype  is   perfp_vow
πέπεισμαι   stemtype  is   perfp_d
γέγραμμαι    stemtype    is   perfp_p 
πέπραγμαι    stemtype    is      perfp_g
ἤγγελμαι      stemtype     is     perfp_l
πέφασμαι     stemtype    is     perfp_n
would it be possible for each stemtype to highlight only the correspondent cell?

**Comment by monzug** [comment]
similar scenario in verbpdgm15 table
in rules.csv, we ignore the stemtype for the mediopassive verbs so all cells are highlighted. However  we consider the stemtype only for the active form.
verbpdgm15	3	verb	perf_act	active		pluperfect
the other stemtype are:
perfp_vow   for    vowel stem
perfp_d       for   dental plosive stem
perfp_p       for   labial plosive stem
perfp_g      for    velar plosive stem
perfp_l       for    stem in λ
perfp_n      for    stem in ν

**Comment by irina060981** [comment]
I believe that this bug could be solved by adding to paradigm cell properties stem_type

for example `verbpadgm12` - first row with data
![image](https://user-images.githubusercontent.com/12377640/72140245-0e106a80-33dc-11ea-8bd1-3ad989272df4.png)

```
{"cells": [
            {
                "role": "label",
                "tense": "perfect",
                "voice": "mediopassive middle",
                "mood": "indicative",
                "value": "singular"
            },
            {
                "role": "label",
                "tense": "perfect",
                "voice": "mediopassive middle",
                "number": "singular",
                "mood": "indicative",
                "value": "1st"
            },
            {
                "role": "data",
                "tense": "perfect",
                "voice": "mediopassive middle",
                "number": "singular",
                "person": "1st",
                "mood": "indicative",
               **"stemtype": "perfp_vow",**
                "value": "λέλυμαι"
            },
            {
                "role": "data",
                "tense": "perfect",
                "voice": "mediopassive middle",
                "number": "singular",
                "person": "1st",
                "mood": "indicative",
               **"stemtype": "perfp_d",**
                "value": "πέπεισμαι"
            },
            {
                "role": "data",
                "tense": "perfect",
                "voice": "mediopassive middle",
                "number": "singular",
                "person": "1st",
                "mood": "indicative",
                **"stemtype": "perfp_p",**
                "value": "γέγραμμαι"
            }
        ]},
```

And so on. And check matching.
@balmas , what do you think?

**Comment by balmas** [comment]
yes adding the stemtype to the cell data should help this. Similar to #301

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
webextension 3.0.6-qa.1 (components 1.6.0-dev)

**Comment by monzug** [comment]
tested in Firefox  Alpheios Reading Tools 3.0.6.97
Alpheios Components 1.6.0-dev
