### ISSUE TITLE
a mistake in the paradigm table for the dual indicative active of ἵστημι

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#308]
the 3rd person dual indicative active of ἵστημι (in addition to forms from ἕστηκα)   should be   ἑστάτην     and not   ἕστατον
lookup for    ἕστατον   will highlight only the 2nd person dual
lookup for    ἑστάτην   will highlight the 3rd person dual
we should correct the error on our side originated from the Athematic Perfects, table 17 in https://ucbclassics.dreamhosters.com/ancgreek/paradigmsU/paradigms_U.html
from Morpheus:
<infl>
<term xml:lang="grc">
<stem>ἑστ</stem>
<suff>άτην</suff>
</term>
<pofs order="1">verb</pofs>
<mood>indicative</mood>
<num>dual</num>
<pers>3rd</pers>
<tense>pluperfect</tense>
<voice>active</voice>
<stemtype>perf2_act</stemtype>
</infl>
<infl>
<term xml:lang="grc">
<stem>ἑστ</stem>
<suff>άτην</suff>
</term>
<pofs order="1">verb</pofs>
<mood>indicative</mood>
<num>dual</num>
<pers>3rd</pers>
<tense>perfect</tense>
<voice>active</voice>
<stemtype>perf2_act</stemtype>
</infl>

**Comment by irina060981** [comment]
>lookup for ἕστατον will highlight only the 2nd person dual

![image](https://user-images.githubusercontent.com/12377640/72058034-2a000780-331b-11ea-8d3e-4421b6236717.png)

> lookup for ἑστάτην will highlight the 3rd person dual

![image](https://user-images.githubusercontent.com/12377640/72058091-400dc800-331b-11ea-8b0e-6dc9248f1f64.png)

![image](https://user-images.githubusercontent.com/12377640/72058258-86fbbd80-331b-11ea-808a-6d2f06ec6bc5.png)

Tables are the same
Forms highlighted according to morph properties

@monzug , what exactly should be fixed on our side? Could you give more detailed information?

**Comment by monzug** [comment]
The table is wrong. As said it should be ἑστάτην

**Comment by irina060981** [comment]
@monzug , do you mean to change
dual 3rd indicative from `ἕστατον` => `ἑστάτην`
?

**Comment by balmas** [comment]
ok, per @monzug this seems to be a straightforward error in the table data.  

```
 {
                "role": "data",
                "tense": "perfect",
                "number": "dual",
                "person": "3rd",
                "mood": "indicative",
                "value": "ἕστατον"
            },

```

should be changed to 

```
 {
                "role": "data",
                "tense": "perfect",
                "number": "dual",
                "person": "3rd",
                "mood": "indicative",
                "value": "ἑστάτην"
            },
```

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
webextension 3.0.6-qa.1 (components 1.6.0-dev)

**Comment by monzug** [comment]
YES, thanks!
