### ISSUE TITLE
greek adjective tables

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#31]
we need to add the greek adjective tables

**Comment by balmas** [comment]
@irina060981 see discussion in the Slack check-ins channel about Inflection Tables before looking at this.

@kirlat I think it might be better to use the new vue component structure for all new inflection tables going forward. What do you think?

**Comment by irina060981** [comment]
We have discussed with @kirlat and he told me to make a pull request for these work.
His part with be applied to this later.

**Comment by irina060981** [comment]
A new table
![image](https://user-images.githubusercontent.com/12377640/41775950-49f3b4a8-7669-11e8-871a-59a4a0c29905.png)

**Comment by irina060981** [comment]
From v1
![image](https://user-images.githubusercontent.com/12377640/41775987-664b64d4-7669-11e8-85ae-cbc711a38382.png)

**Comment by irina060981** [comment]
1) Uploaded alph-infl-adjective.xml
2) Added to converter.js a part for adjectives
3) Converted to adjective/suffixes.csv and adjective/footnotes.csv
4) Added greek-adjective-simplified-view and greek-adjective-view

**Comment by irina060981** [comment]
Merged and closed
