### ISSUE TITLE
should we add an other ending to the δέδια (in addition to forms from δέδοικα) table?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#313]
in the paradigm table, one ending for the 2nd person imperative is missing.
lookup for    δέδιε    -     Morpheus says that it's a 2nd person imperative and 3rd person singular indicative. shall we add this ending to the existing imperative 2nd person singular  δέδιθι   ?
<infl>
<term xml:lang="grc">
<stem>δεδι</stem>
<suff>ε</suff>
</term>
<pofs order="1">verb</pofs>
<mood>imperative</mood>
<num>singular</num>
<pers>2nd</pers>
<tense>perfect</tense>
<voice>active</voice>
<stemtype>perf_act</stemtype>
</infl>
<infl>
<term xml:lang="grc">
<stem>δεδι</stem>
<suff>ε</suff>
</term>
<pofs order="1">verb</pofs>
<mood>indicative</mood>
<num>singular</num>
<pers>3rd</pers>
<tense>perfect</tense>
<voice>active</voice>
<stemtype>perf_act</stemtype>
</infl>

**Comment by monzug** [comment]
same as issue #221

**Comment by irina060981** [comment]
Now it is
![image](https://user-images.githubusercontent.com/12377640/72055622-e5726d00-3316-11ea-9fac-eddc80e9001d.png)

I could add δέδιε

![image](https://user-images.githubusercontent.com/12377640/72055666-f9b66a00-3316-11ea-9641-001bba8888c1.png)

@balmas , should I do this?

**Comment by monzug** [comment]
I would add δέδιε to the imperative as we are looking at the same table.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
webextension 3.0.6-qa.1 (components 1.6.0-dev)

**Comment by monzug** [comment]
tested in Firefox  Alpheios Reading Tools 3.0.6.97
Alpheios Components 1.6.0-dev
