### ISSUE TITLE
in rules.csv please change acive in active  in line 74

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#315]
verbpdgm34	3	verb		acive		aorist	ἵημι

**Comment by monzug** [comment]
Bridget, if u want i can fix this.

**Comment by balmas** [comment]
yes please @monzug

**Comment by monzug** [comment]
will do next

**Comment by balmas** [comment]
qa-3.0.4.94/components 1.5.1

**Comment by monzug** [comment]
active has been fixed in latest build qa-3.0.4.94
