### ISSUE TITLE
missing a match for ἀγάγῃ

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#318]
ἀγάγῃ   is  subjunctive singular 2nd aorist mediopassive with stemtype aor2
and subjunctive singular 3rd aorist active with  stemtype aor2
we do only display the Strong (2nd) Aorist System Active table and not the mediopassive.

maybe we don't show the mediopassive table because in rules.csv it says middle (line 14), verbpdgm7 table.

**Comment by monzug** [comment]
also ἀγάγωμαι does not have the inflection icon (it's middlepassive but in rules.csv we say middle only)

**Comment by monzug** [comment]
I think we should add an other line in rules.csv:
verbpdgm7	1	verb	aor2	middle	
verbpdgm7      1(?)  verb aor2 mediopassive   subjunctive (not sure if we should specify the verb here)

**Comment by irina060981** [comment]
@monzug , we could add such a rule
verbpdgm7,1,verb,aor2,mediopassive,subjunctive,,,,

And this table would be added, but it won't have a match (because verbpdgm7 has only middle)
![image](https://user-images.githubusercontent.com/12377640/71976983-71c35800-3263-11ea-8d1b-c1fde0dffbde.png)

May be we should add table for mediopassive ?

**Comment by balmas** [comment]
I think maybe we should allow middle and mediopassive to be interchangeable when it comes to matching into the cells of the table if there isn't contradictory data in the inflection (i.e. middle + active would never equal mediopassive) . What do you think @monzug ?

**Comment by monzug** [comment]
interesting. I thought that by adding the mediopassive line it would work. maybe we should not use the subjective field?  it does work for other verbs to have one line with middle and one with mediopassive in rules.csv. 
@balmas, I am just puzzled that it does not work... I am always for the easy solution. I am afraid your suggestion would add an extra layer to an already fragile construction.

**Comment by balmas** [comment]
@monzug can you give me an example of where a form reported as mediopassive matches into a middle table cell?

**Comment by monzug** [comment]
in rules.csv, we have
verbpdgm25,2,verb,ajw_pr,mediopassive,,,,,
verbpdgm25,2,verb,ajw_pr,middle,,,,,

**Comment by monzug** [comment]
e.g.  ὁρῶ  is  <infl>
<term xml:lang="grc">
<stem>ὁρ</stem>
<suff>ῶ</suff>
</term>
<pofs order="1">verb</pofs>
<mood>imperative</mood>
<num>singular</num>
<pers>2nd</pers>
<tense>present</tense>
<voice>middle</voice>
<stemtype>aw_pr</stemtype>
<derivtype>a_stem</derivtype>
<morph>contr</morph>
</infl>
<infl>
<term xml:lang="grc">
<stem>ὁρ</stem>
<suff>ῶ</suff>
</term>
<pofs order="1">verb</pofs>
<mood>imperative</mood>
<num>singular</num>
<pers>2nd</pers>
<tense>present</tense>
<voice>mediopassive</voice>
<dial>epic</dial>
<stemtype>aw_pr</stemtype>
<derivtype>a_stem</derivtype>
<morph>contr</morph>
</infl>

**Comment by irina060981** [comment]
I belive we could close it too - it was fixed within https://github.com/alpheios-project/inflection-tables/issues/296

ἀγάγῃ

![image](https://user-images.githubusercontent.com/12377640/72775528-6f490100-3c5a-11ea-82fb-067591b700c8.png)

@monzug and @balmas , what do you think?

**Comment by monzug** [comment]
great. I thought it would work by adding the mediopassive line. I will reassign to me so to verify. Thanks.

**Comment by irina060981** [comment]
Thank you, Monica!

**Comment by monzug** [comment]
fixed by #296
