### ISSUE TITLE
Move paradigm matching cell to inflections table repo

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/inflection-tables#320]
Discussed https://github.com/alpheios-project/inflection-tables/pull/312
https://github.com/alpheios-project/inflection-tables/issues/289
We need to move all matching logic to inflectins repo abd create tests for paradigm matching cells.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
will be tested generally with regressions.
