### ISSUE TITLE
greek articles table

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#33]
add the greek articles table

**Comment by irina060981** [comment]
https://github.com/alpheios-project/inflection-tables/pull/54

1.created in converter.js a part for greek articles
2.converted alph-infl-article.xml to forms.csv
3.added addArticleFormsto greek-language-dataset.js and added to getObligatoryMatchList, getOptionalMatchList
4.created greek-numeral-view.js

it need to be used with - alpheios-project/data-models#36

**Comment by irina060981** [comment]
Merged and closed
