### ISSUE TITLE
remove dialect from paradigm matching rules

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#335]
we have dialects all over the place in Greek verbs but verbpdgm5  is the only one who has the dialect in rules.csv and it does not work. So, I would give a try first by removing the dialect and see if it works. I am suspicious as it's the only place where we have it. 

_Originally posted by @monzug in https://github.com/alpheios-project/inflection-tables/issues/289#issuecomment-560420110_

**Comment by monzug** [comment]
this is issue #300

**Comment by balmas** [comment]
oops. thanks! marking as dupe.
