### ISSUE TITLE
greek paradigms - issue summary

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#342]
I think the *existing* problems we have found with the Greek paradigms generally fall into one of these categories:

1) A form included in a paradigm table is questionable (maybe projected and not actually attested in the literature). 

2) Forms attested in the literature are missing from a paradigm table (maybe because of a dialectical variation)

3) Morpheus fails to analyze a form so we can't match it to a table.

4) The data provided by morpheus analysis does not match the rules we have set for what should be the corresponding paradigm table

5) The rules we have set for matching a form to a paradigm are too restrictive

6) The rules we have set for matching a form to a paradigm are wrong

7) The rules we have set for matching a form to a paradigm are too expansive

8) We match to the right table but the properties of either the table data or the morpheus data don't match so we cannot highlight the correct form in the table

9) we aren't sure what table we *should* be showing for a given form

10) we don't have any way to test to be sure a change in a matching rule for one form doesn't break matching for other forms that depend upon that rule

@irina060981 and @monzug have a I missed anything in this list that you can think of?

**Comment by vgorman1** [comment]
Isn’t Greek fun?


Vanessa B. Gorman
Professor, Ancient History
Undergraduate Chair
Dept. of History
University of Nebraska-Lincoln
619 Oldfather Hall
Lincoln, NE 68588-0327

**Comment by monzug** [comment]
well, it's all correct but it sounds worse that it is in reality. Most of the time the match works and works beautifully!!!!! and yes, Greek is really interesting

**Comment by balmas** [comment]
All of that said, even if the morpheus data and the paradigm table was "perfect" it is probably not possible to devise rules that work all the time for all forms.

I would like us to consider the following questions

1) Should back off of trying to match forms to tables entirely, and just show the user all of the paradigms and let them figure out for themselves which one applies?

2) Should we try to use the morpheus data to filter the tales to show, but in a less precise way, leaning towards showing any table that we think *might* have a match?

3) If we continue to use algorithmic rules, how can we improve the process of automatically testing the matching results so that we can confident they work and that changes to rules don't break anything?

4) If we add support for the ability for someone publishing a page of Greek text to indicate to alpheios on a word-by-word level which paradigm to show in that particular instance (comparable to the way we enable identification of treebank diagrams right now), how would that interact with the existing logic for identifying the paradigm? Should we only show the identified table?  Would there be value in harvesting this data to build up a databank of matches of forms to tables that could be used wherever that form appears?

**Comment by balmas** [comment]
@monzug @vgorman1 and @irina060981 these questions are the ones I would like us to discuss tomorrow, with a specific goal of identifying what is the minimum functionality wrt to the inflection tables that Vanessa needs working for the fall semester.

**Comment by balmas** [comment]
Summary of decisions from today's discussion:

1) More useful than perfect matching of a specific form correctly to a specific tables would be to group the paradigm tables by type of verb, similar to the way they are presented in Smyth and other grammars, and then match a form to the corresponding group.

2) Including dialectical variants in the tables or matching perfectly on them is not a priority

3) Reinserting the links from the Greek inflection tables to the grammars would be very helpful.  (that's #197 )

4) Particularly for abnormal verbs, it would be helpful to show the principal parts

5)  Still would be useful to have the noun and adjective paradigms included, but adding custom paradigm tables is not a priority.  (Whereas  being able to correct the definitions and improve on the missing parses , contractions, etc. is really needed)

6) Testing/optimization should focus on the most commonly used forms

7) Smyth should be the grammar of reference when there are questions (but it might be useful to get a copy of the new Cambridge Grammar of Classical Greek)

@vgorman1 will 

1) provide a list of common verb forms and the paradigms they should match to (she will reference Smyth, we will then need to map from Smyth back to the corresponding Mastronarde table)

2) look for resources for principal parts

3) continue to gather missing/incorrect definitions

@balmas will begin to work on an infrastructure for augmenting the parses provided by legacy morphology engines that allows for easy contribution of new/corrected parses.

@monzug to look at how the Mastronarde tables map to the verb types outlined Smyth and offer suggestions for grouping them in the Alpheios display

@irina060981 will develop unit testing infrastructure for the paradigms and continue to work on adding the noun and adjective paradigms

**Comment by balmas** [comment]
forgot one more for @vgorman1 :  provide list of common greek contractions

**Comment by balmas** [comment]
> @balmas will begin to work on an infrastructure for augmenting the parses provided by legacy morphology engines that allows for easy contribution of new/corrected parses.

design will be documented via alpheios-project/documentation#24

**Comment by balmas** [comment]
> forgot one more for @vgorman1 : provide list of common greek contractions

this is done in #345

**Comment by balmas** [comment]
>@irina060981 will develop unit testing infrastructure for the paradigms and continue to work on adding the noun and adjective paradigms

done via #347  and #284

**Comment by balmas** [comment]
separate issues entered for all action items. closing this one now.
