### ISSUE TITLE
paradigm test script

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#355]
@balmas, I started to work on the prototype and created a simple parsing of existed paradigms tables (based on the vue-cli-4) - I published on my server for now

http://alpheios-infl-check.irina-sklyarova.ru/

_Originally posted by @irina060981 in https://github.com/alpheios-project/inflection-tables/issues/289#issuecomment-557513766_

**Comment by balmas** [comment]
@irina060981 can we turn you test interface into a script that can be used to help automatically test a batch of words?

We would like to prioritize testing inflection table matching and identification of additional enhancements needed by putting a list of most commonly use forms through such a script to get out for each form:

1) the lemma(s) identified with the stemtypes
2) the table(s) matched
3) the cells matched within those tables 

I think your little test interface is actually almost all the way there to what we need. It just would need a few additional features:

1) inclusion of the lemma in the output
2) inclusion of the cells matched in each matched table
3) the ability to accept an uploaded list of forms as input
4) the ability to mark errors and export them to a file
5) a nice to have, but not essential, would be a link from each matched table to the actual table display

What do you think?

**Comment by balmas** [comment]
Also, @monzug can you think of anything else that would be needed in this interface?

**Comment by monzug** [comment]
@balmas, as per your question, what we need is
lemma
verb
mood
num
pers
tense
voice
stemtype
derivtype

that's all I have been using for matching + grammars... but let's not go there

**Comment by monzug** [comment]
Forget to mention the dialect field e.g. <dial>Homeric Ionic</dial>

**Comment by irina060981** [comment]
@balmas and @monzug, I have updated prototype
http://alpheios-infl-check.irina-sklyarova.ru/

it works this way.
You could pass words separated by comma
![image](https://user-images.githubusercontent.com/12377640/73840426-e1793280-4863-11ea-90b2-513f72f6ef99.png)

click **Get the word**

![image](https://user-images.githubusercontent.com/12377640/73840445-eb9b3100-4863-11ea-8aa6-cc28906ca53c.png)

Each line is collapsible

![image](https://user-images.githubusercontent.com/12377640/73843473-754dfd00-486a-11ea-8d78-08bb819fcb85.png)

**Comment by irina060981** [comment]
I have uploaded source code here
https://github.com/alpheios-project/inflection-input

all calculations are recieved from `inflection-tables`

**Comment by irina060981** [comment]
@balmas, I hope I made the folloing points:

> 
- the lemma(s) identified with the stemtypes
- the table(s) matched
- the cells matched within those tables
- inclusion of the lemma in the output
- inclusion of the cells matched in each matched table
- the ability to accept an uploaded list of forms as input

**Comment by irina060981** [comment]
> the ability to mark errors and export them to a file
here I don't understand, how do you see this - in this interface?
similiar to Wikipedia? you should have ability to select something, get the form, add the note, save somewhere and then download?

oh it is simply some memo to print some text?

> a nice to have, but not essential, would be a link from each matched table to the actual table display

Here I didn't understand - what do you mean.
I have done rendered tables with fullMatch cells, may be it is enough?

@balmas and @monzug , would be happy to get your feedback :)

**Comment by balmas** [comment]
> the ability to mark errors and export them to a file
here I don't understand, how do you see this - in this interface?
similiar to Wikipedia? you should have ability to select something, get the form, add the note, save somewhere and then download?

The point of the interface is enable efficient QA of the table matching algorithm.  Rather than require the user to keep a separate list somewhere of the errors, I think it would be helpful to just be able to mark the errors in the review interface and then be able to download the list. Maybe the interface could offer something like the following:
![Test Paradigm Inflection](https://user-images.githubusercontent.com/644870/73847629-ad1a5d80-47f4-11ea-87d1-530d2523008a.png)

And then a download button to download the inputs as a CSV file?

**Comment by balmas** [comment]
>I have done rendered tables with fullMatch cells, may be it is enough?

Yes I think that works.

**Comment by balmas** [comment]
Regarding the inputs, we are probably going to do batches of 25 or 100 words at a time. So the ability to upload a text file with the list of words would be helpful.

**Comment by monzug** [comment]
Irina, fantastic tool. Thanks so much.
would it be possible to add the translation of the lemma?

**Comment by irina060981** [comment]
>The point of the interface is enable efficient QA of the table matching algorithm. Rather than require the user to keep a separate list somewhere of the errors, I think it would be helpful to just be able to mark the errors in the review interface and then be able to download the list. Maybe the interface could offer something like the following:
And then a download button to download the inputs as a CSV file?

Oh I think it is a good idea! Didn't guess to it :)

**Comment by irina060981** [comment]
>Regarding the inputs, we are probably going to do batches of 25 or 100 words at a time. So the ability to upload a text file with the list of words would be helpful.

ok, let's do it!

**Comment by irina060981** [comment]
>Irina, fantastic tool. Thanks so much.
would it be possible to add the translation of the lemma?

thank you, Monica! 
@monzug, do you mean translations to some languages from lemma-translation service?
Or short definitions from dictionaries?

**Comment by monzug** [comment]
short definitions, if it's possible. Thanks for asking

**Comment by irina060981** [comment]
>short definitions, if it's possible. Thanks for asking

oh great, than my thoughts were right :)

I have made the following changes:

Would be this way
![image](https://user-images.githubusercontent.com/12377640/73910312-bd1c6500-48fa-11ea-9d3a-f745d28f923d.png)

after choose file 

![image](https://user-images.githubusercontent.com/12377640/73910327-c6a5cd00-48fa-11ea-9a04-fcf4912765a3.png)

Also added short definitions checkbox and add them to the result

![image](https://user-images.githubusercontent.com/12377640/73919116-aa139000-490e-11ea-860d-e86800204b54.png)

**Comment by irina060981** [comment]
> > the ability to mark errors and export them to a file
> > here I don't understand, how do you see this - in this interface?
> > similiar to Wikipedia? you should have ability to select something, get the form, add the note, save somewhere and then download?
> 
> The point of the interface is enable efficient QA of the table matching algorithm. Rather than require the user to keep a separate list somewhere of the errors, I think it would be helpful to just be able to mark the errors in the review interface and then be able to download the list. Maybe the interface could offer something like the following:
> ![Test Paradigm Inflection](https://user-images.githubusercontent.com/644870/73847629-ad1a5d80-47f4-11ea-87d1-530d2523008a.png)
> 
> And then a download button to download the inputs as a CSV file?

I have to do only feedback feature, the other points are made.

**Comment by balmas** [comment]
this is up now at https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/inflection-input/index.html
