### ISSUE TITLE
latin irregular verbs

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#36]
we need to finish the Latin irregular verb tables

**Comment by balmas** [comment]
I believe that I already imported the data for the Latin irregular verbs in the forms.csv in lib/latin/lang/data/verb

Views need to be created and matching rules implemented.

@irina060981 see discussion in the Slack check-ins channel about Inflection Tables before looking at this.

@kirlat I think it might be better to use the new vue component structure for all new inflection tables going forward. What do you think?

**Comment by irina060981** [comment]
Closed and merged with additonal PR in components and data-model
