### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#38]
we need to add unit tests for each table that cover for each cases of 
- full match
- partial match
- no match

**Comment by balmas** [comment]
while it would be good to have these, I think it might make sense to wait until we have time to port all the tables to the newer vue component structure.

**Comment by irina060981** [comment]
1 step for unit tests - simple tests for current version of files - besides views variants
https://github.com/alpheios-project/inflection-tables/tree/infl-tests

**Comment by irina060981** [comment]
I agree - that we should wait for newer component structure

**Comment by irina060981** [comment]
@balmas , what do you think - is this issue actual for now?
Should I find time to create some specific tests here or may be we could close this issue too?

**Comment by balmas** [comment]
let's leave it open. We do need unit tests and I don't want to forget about that, but it is not the highest priority at the moment.

**Comment by irina060981** [comment]
@balmas, as I have done a lot of new tests for views and data - may be we should close this issue?

**Comment by balmas** [comment]
agree
