### ISSUE TITLE
greek verb paradigms: add links to participle declension paradigm tables

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#42]
In the V1 version, we linked from the paradigm subtables to participle declension paradigm tables. These links are embedded in the original src xml as reflinks: 

`<reflink xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="inflect:#verb|type:paradigm|paradigm_id:verbpdgm54">`

We want similar functionality in V2

**Comment by kirlat** [comment]
Do I understand correctly that a link such as `inflect:#verb|type:paradigm|paradigm_id:verbpdgm54` should show a paradigm table with `verbpdgm54` ID? If this paradigm table have a sub table, should we show that as well?

V1 opens a linked table in a separate pop-up window. What should we do in V2? Should we show it below the main table on the same page, possible hidden, and scroll to it when user clicks on a link?

**Comment by balmas** [comment]
Yes, that is correct: A link such as inflect:#verb|type:paradigm|paradigm_id:verbpdgm54 should show a paradigm table with verbpdgm54 ID

I think we could approach it as you suggest. We could also replace the current table with the linked to table as the currently selected view, but then we would probably want navigation back and forth between them. For now your suggestion might be simplest.

**Comment by balmas** [comment]
A few thoughts:

Can we show the titles of the extra declension tables? 

I'm also trying to think how we can keep the conceptual linkage between the references participle tables and the related tables shown below. Not sure if it really matters that much though.

**Comment by kirlat** [comment]
Titles for extra tables is a great idea, will add them.

What should the linkage signify? Should we show in a supplemental table to what word or what type of word is it related to? Should we provide a way to jump back to the main table? Maybe we should use different color on "see declension" links and use the same accent color on supplemental tables to indicate what table is related to what cell (when there are multiple supplemental tables)?

**Comment by balmas** [comment]
hmm. I like all of these ideas :-) I like the idea of using colors to link the tables and in-page links back and forth would also be good.

**Comment by kirlat** [comment]
I made some changes to implement a preliminary vision of a concept. There are 5 color defined. Depending on a number of linked tables, corresponding colors are used to highlight a link to a supplemental table and a supplemental table itself. If all five colors are used, they will be reused starting from the first one.

I also added a nav link below a linked table that scrolls content to the top of the main table.

Please let me know what do you think. Do you have any other ideas how to implement this? Thanks!

**Comment by kirlat** [comment]
Updated highlighting rules so that only then linked paradigm tables be selected when there is more than one linked table within a panel.

**Comment by kirlat** [comment]
Should be fixed by now in `master`, please let me know if not
