### ISSUE TITLE
greek verb paradigms: add explanatory hint

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#43]
when we match into a verb paradigm table, we want to show a hint that indicates that the current table is representative patters for verbs similar to the one chosen.

e..g from V1

"The following table(s) show conjugation patterns for verbs which are similar to those of "ἔννεπε".

**Comment by balmas** [comment]
In the latest build, the hint is there in the source, but display is set to none so it doesn't show up.

**Comment by kirlat** [comment]
Should be fixed by now in `master`, please let me know if not
