### ISSUE TITLE
verify Greek verb paradigm matching

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#50]
E.g. see βουλεύσεται
In V1 this matches 
Future System (without contraction)
Weak (1st) Aorist System Middle

In V2 we get those 2 tables plus an extra one:
 ἵημι: Aorist System Middle

I'm not positive which is right, so it needs investigating

**Comment by balmas** [comment]
another example from #51:

"οὖσᾰ", according to rules, there must be three matches. in V1 we got 2, tables 57 and 60 only.
For verb participle form of this word, morphological analyzer returns two inflections;
```
lemma: εἰμί
    Inflection 1:
        gender feminine
        number singular
        case nominative
        mood participle
        voice active
        stemtype irreg_mi
        tense present
    Inflection 2:
        gender feminine
        number singular
        case vocative
        mood participle
        voice active
        stemtype irreg_mi
        tense present
```
Those inflection matches three rules (I've shown titles of corresponding tables for clarity):
```
Participles in -ών, -οῦσα, -όν (strong aorist active; present of εἰμί and εἶμι)
<match paradigm_id_ref="verbpdgm57" match_order="13">
  <constraint name="pofs">verb_participle</constraint>
  <constraint name="stemtype">irreg_mi</constraint>
  <constraint name="tense">present</constraint>
  <constraint name="lemma">εἰμί</constraint>
</match>

Participles in -άς, -ᾶσα, -άν (μι-verb present and aorist active)
<match paradigm_id_ref="verbpdgm59" match_order="12">
  <constraint name="pofs">verb_participle</constraint>
  <constraint name="stemtype">irreg_mi</constraint>
</match>

Participles in -είς, -εῖσα, -έν
<match paradigm_id_ref="verbpdgm60" match_order="13">
  <constraint name="pofs">verb_participle</constraint>
  <constraint name="stemtype">irreg_mi</constraint>
  <constraint name="voice">active</constraint>
</match>
```

**Comment by balmas** [comment]
#61 and #62 have been entered as bugs for these. Closing this issue now in favor of those.

**Comment by monzug** [comment]
related to issue #289 
the original issue is about the matching of  βουλεύσεται
as per above comment, we used to get an extra table that now is gone. However the original match was done on verbpdgm3 - Future System (without contraction) - and verbpdgm9 - Weak (1st) Aorist System Middle
Unfortunately, now it's done on the  verbpdgm4 - Future System (Active and Middle) with contraction in -έω 
this is again an other consequences of the rules.csv as verbpdgm4 has higher matchOrder
verbpdgm3	1	verb	reg_fut						
verbpdgm4	3	verb	reg_fut					contr	
verbpdgm3	1	verb	aw_fut						
verbpdgm4	2	verb	aw_fut					contr	
verbpdgm3	1	verb	ew_fut						
verbpdgm4	2	verb	ew_fut					contr

**Comment by balmas** [comment]
> related to issue #289
> the original issue is about the matching of βουλεύσεται
> as per above comment, we used to get an extra table that now is gone. However the original match was done on verbpdgm3 - Future System (without contraction) - and verbpdgm9 - Weak (1st) Aorist System Middle
> Unfortunately, now it's done on the verbpdgm4 - Future System (Active and Middle) with contraction in -έω
> this is again an other consequences of the rules.csv as verbpdgm4 has higher matchOrder
> verbpdgm3 1 verb reg_fut
> verbpdgm4 3 verb reg_fut contr
> verbpdgm3 1 verb aw_fut
> verbpdgm4 2 verb aw_fut contr
> verbpdgm3 1 verb ew_fut
> verbpdgm4 2 verb ew_fut contr

This is going to be covered by #336 so reclosing this issue in favor of that one.
