### ISSUE TITLE
match greek verb participles

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#51]
We have tables for verb participles and should match on them

e.g. 

οὖσᾰ

should match verbpdgm57

**Comment by kirlat** [comment]
Made a fix in https://github.com/alpheios-project/webextension/tree/issue-inflection-tables-51. I've also found an error in matching rules checking and fixed it. Now it matches more tables than V1, but that seems to be correct, at least formally.

For example, for a word "οὖσᾰ", according to rules, there must be three matches.
For verb participle form of this word, morphological analyzer returns two inflections;
```
lemma: εἰμί
    Inflection 1:
        gender feminine
        number singular
        case nominative
        mood participle
        voice active
        stemtype irreg_mi
        tense present
    Inflection 2:
        gender feminine
        number singular
        case vocative
        mood participle
        voice active
        stemtype irreg_mi
        tense present
```
Those inflection matches three rules (I've shown titles of corresponding tables for clarity):
```
Participles in -ών, -οῦσα, -όν (strong aorist active; present of εἰμί and εἶμι)
<match paradigm_id_ref="verbpdgm57" match_order="13">
  <constraint name="pofs">verb_participle</constraint>
  <constraint name="stemtype">irreg_mi</constraint>
  <constraint name="tense">present</constraint>
  <constraint name="lemma">εἰμί</constraint>
</match>

Participles in -άς, -ᾶσα, -άν (μι-verb present and aorist active)
<match paradigm_id_ref="verbpdgm59" match_order="12">
  <constraint name="pofs">verb_participle</constraint>
  <constraint name="stemtype">irreg_mi</constraint>
</match>

Participles in -είς, -εῖσα, -έν
<match paradigm_id_ref="verbpdgm60" match_order="13">
  <constraint name="pofs">verb_participle</constraint>
  <constraint name="stemtype">irreg_mi</constraint>
  <constraint name="voice">active</constraint>
</match>
```
So, it seems to me that showing three tables is correct. However, V1 shows only two. Is there some flaw in my logic here? Could you please check it? You can use a `issue-inflection-tables-51` branch of `webextension` to check out a corresponding code.

Thanks!

**Comment by kirlat** [comment]
This should be in master, please let me know if it is not working as expected.

**Comment by balmas** [comment]
Re the additional table, agree the matching is currently applying the rules as expected. Whether or not this is actually what we want is another question though. Per discussions with @abrasax it may be that we were already matching too many tables in V1 as well, but we need a Greek expert to help us make that decision. Issue #50 addresses this question so this item can be closed.

**Comment by balmas** [comment]
actually, there are some problems with the match order logic, see new issues #61 and #62
