### ISSUE TITLE
Greek language - if compare suffix - ής and ης - they won't have suffixMatch

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/inflection-tables#60]
The greek adjective - **"συνεχής" ( συνεχ - ης )**
Target word has suffix - **ής**
Lexemes from morph-analyzer - have suffix - ης

As we use inflectionData from lexemes - we compare only **ης** with suffix variants, so we miss **ής**
for comparing in LanguageDataset.matcher with use Inflection.compareWithWordDependsOnType => that uses String.normalize

but 'ης'.normalize('NFC') !==ής .normalize('NFC')

**Comment by irina060981** [comment]
In the old version
![image](https://user-images.githubusercontent.com/12377640/42886190-483ba85a-8ae6-11e8-83ed-677acf8eb7bd.png)

**Comment by irina060981** [comment]
In the new version
![image](https://user-images.githubusercontent.com/12377640/42886230-5b16b500-8ae6-11e8-935a-48f1c3deac05.png)

**Comment by balmas** [comment]
@abrasax I think we intentionally ignored accents when highlighting matching endings in the inflection tables in V1 (and we warned the users of that with the hint). Do we want to continue to do the same? Or is this a decision to revisit?

**Comment by balmas** [comment]
Assigning to @monzug for her opinion on this.  Should we continue to ignore accents when matching the greek inflections endings as we did in V1?

**Comment by monzug** [comment]
I would ignore accents as we did in V1. I read few things about Greek accents and many believe that they were introduced later. Accordingly to the following article:  http://atticgreek.org/accent/acc_marking4.html
there are few words in which the accents are crucial. Unfortunately we are missing some matches on the inflection table such as βουλεῦσαι    aorist infinitive (active)
and δικαία 
Maybe, by ignoring the accents we could improve the matching on the inflection tables.

**Comment by monzug** [comment]
More on the original issue. in the latest buil 2.0.2.2 the 3rd adj declension is missing. when lookup
συνεχής the related inflection tables are 1st and 2nd adj decl

![screenshot_2018-08-18 screenshot](https://user-images.githubusercontent.com/41396793/44300044-7e41bc00-a2ce-11e8-8977-a9408ed86f23.png)

**Comment by balmas** [comment]
still need to give you a build for this

**Comment by balmas** [comment]
test case for this from 131: Greek πρόσφυμα (morpheus engine says the suffix is μα, the table has α)

**Comment by balmas** [comment]
Ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-5

**Comment by monzug** [comment]
tested in chrome in build 2.0.3-5
σκληρή  matches both endings η ,  ή , 
and  συνεχής  matches both endings ής , ης 
for the noun table, I used ξηρή who matches 3 endings , η  , ή  , ῆ
