### ISSUE TITLE
consider lemma in paradigm matching rules

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#61]
Some of the Greek verb paradigm matching rules include the lemma but it looks like this isn't being considered in the Paradigm#matches function, which only checks the features of the inflection against the rule features and not the lemma.

This results in, for example verbpgdm32 being shown for all active verbs rather than just those with the lemma `ἵημι`  (e.g. test with ἔννεπε)

**Comment by kirlat** [comment]
Will work on that

**Comment by balmas** [comment]
@monzug can you test this in the https://github.com/alpheios-project/webextension/tree/issue-inflection-tables-61-62 branch ? You can download it from https://github.com/alpheios-project/webextension/archive/issue-inflection-tables-61-62.zip

**Comment by monzug** [comment]
ἔννεπε shows two matches (s. pr imp act and s. imp. ind. act)

**Comment by monzug** [comment]
for  "οὖσᾰ" ( οὖσα ), to be to exist - there are two matches with verb participle:
1) λιποῦσᾰ  Participles in -ών, -οῦσα, -όν (strong aorist active; present of εἰμί and εἶμι)
λιποῦσᾰ (leave, quit or to be sleek, radiant)
2) τιθεῖσᾰ    Participles in -είς, -εῖσα, -έν
τιθεῖσᾰ  (set, put, place)
I was expecting to be table

**Comment by balmas** [comment]
Some comments:

With this fix it seems that we are now getting the correct results for ἔννεπε - i.e. we are no longer getting matches into the table for ἵημι which is restricted by lemma.

The issue with οὖσα, which is the subject of #62 also appears to be fixed, in that it obeys the matchOrder and filters out the matches with a lower order (and the V2 results now are the same as in V1).  But @monzug has raised a good question about whether or not those rules are actually correct or sufficient.  @abrasax also raised this question about why we are showing the match on the 2nd table, (Participles in -είς, -εῖσα, -έν).  This is now entered as #72.

I recommend closing this issue and #62 and merging the fixes into master since these bugs seem fixed as reported. @monzug do you agree?

**Comment by monzug** [comment]
yes!

**Comment by kirlat** [comment]
I will submit a PR then

**Comment by monzug** [comment]
Thanks!

**Comment by balmas** [comment]
closing this as it has been merged to master.
