### ISSUE TITLE
Irregular verbs: compounds of sum 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#70]
all the compounds verbs of sum such as adsum (and absum), desum, insum, intersum, praesum, obsum, prosum, subsum, supersum are missing the correspondent irregular table. I think we should show the irregular sum table. e.g. pro-sum and not pros-um for the verb

**Comment by abrasax** [comment]
yes.

**Comment by balmas** [comment]
@monzug do you mean you want to show the sum table as it currently is (or will be when #83 is fixed) or do you want to show tables that have the conjugations for each of these explicitly, (e.g. a table which has adsum ades etc. ?

**Comment by balmas** [comment]
@monzug : question is the above an exhaustive list of the sum compounds? Or are there many more?

**Comment by balmas** [comment]
@monzug From your comments in https://github.com/alpheios-project/morph-client/issues/15 it seems that the other irregular verb tables (fero, volo, eo, possum) are also for other irregular verbs. Is that correct? I.e. would we want to show the table for volo for malo and nolo?

**Comment by monzug** [comment]
if we show individual tables for each compounds verb, we should do also for malo and nolo. if not,  let me look if they can use the volo ones.

**Comment by monzug** [comment]
malo and nolo are compounds of volo. nolo is for ne-volo and malo is for ma-volo. looking at the table for nolo, we have non vis, non vult, non vultis that would require an additional footnotes in the volo table. maybe showing each table would be better?

**Comment by monzug** [comment]
compound verb of sum: preposition ab, ad, de, in, inter, ob, prae, pro, prod, sub, super
prosum may need its own table because pro retains the d before the e so prodes, prodest etc
fero and all compounds are treated as 3rd conjugation verbs, so are edo and do
eo has few compound verb such as adeo, ineo, veneo, queo
facio is treated as 3rd conj
this is the list of Allen&Greenough.
I know there is also inquam
can we add the verb irregular from drop-down for all irregular verbs and if inflection table is not available, a message pops up saying that table is not available yet?

**Comment by balmas** [comment]
I have alrady added the table for prodsum. We will also implement #109 . I am going to add separate issues for each of the new tables we need to add for the irregular verbs and push them off until the next release.

**Comment by balmas** [comment]
closing this in favor of the individual issues.
