### ISSUE TITLE
should the participle for εἰμί also show the table for Participles in -είς, -εῖσα, -έν (verbpdgm60)

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#72]
According to the matching rules for the Greek Verb Paradigm tables, the match for the participle for εἰμί (οὖσα) produces 2 tables, verbpdgm57 and verbpdgm60. These both have a match order of "13" so they are considered equivalent priority.  However, verbpdgm57 is specific to the lemma εἰμί and perhaps should be the only table matched for participles of that lemma. It's possible that this is just an oversight in the matchOrder (I have no memory of how we came up with those orders in the first place).  It could be fixed by upping the matchOrder of that table to 14 but I am not sure if there is value in showing both tables or not.

The original matching rules were:

```
<match paradigm_id_ref="verbpdgm57" match_order="13">
  <constraint name="pofs">verb_participle</constraint>
  <constraint name="stemtype">irreg_mi</constraint>
  <constraint name="tense">present</constraint>
  <constraint name="lemma">εἰμί</constraint>
</match>

<match paradigm_id_ref="verbpdgm60" match_order="13">
  <constraint name="pofs">verb_participle</constraint>
  <constraint name="stemtype">irreg_mi</constraint>
  <constraint name="voice">active</constraint>
</match>
```

**Comment by balmas** [comment]
These were the results in V1
![screenshot from 2018-08-03 13-01-39](https://user-images.githubusercontent.com/644870/43655632-69522134-971d-11e8-9ab4-a4e17628a88e.png)

And these are the same two tables shown in V2 (following fixes for #61 and #62)
![bibliotheca augustana 1](https://user-images.githubusercontent.com/644870/43655711-c740c25a-971d-11e8-9af1-d25d3700e81f.png)
[
![bibliotheca augustana](https://user-images.githubusercontent.com/644870/43655719-d81108ec-971d-11e8-9259-4683fdbd16f1.png)
](url)

**Comment by balmas** [comment]
@abrasax do you think we should show only the table for Participles in -είς, -εῖσα, -έν when looking up  οὖσα ?

**Comment by balmas** [comment]
We've discussed this and agreed to increase the priority of table 57. Assigning to myself to take care of.

**Comment by monzug** [comment]
related to issue #289 - by changing the matchOrder to table 57, this works as it should now.
