### ISSUE TITLE
Empty inflection table for ipse, ipsa, ipsum

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#73]
lookup the pronoun ipse or ipsa or ipsum. Whitaker output is
ips.e                PRON   6 2 NOM S M                 
ipse, ipsa, ipsum  PRON   [XXXAO]  
himself/herself/itself; the very/real/actual one; in person; themselves (pl.);

click on Inflect, the related inflection table pop-up is empty

**Comment by balmas** [comment]
@monzug I think this is fixed now ... i.e fixed in that you don't get the inflection button anymore. Can you confirm in the issue-inflection-tables-59 build?

**Comment by monzug** [comment]
yes, we do not have the Inflect option available anymore
