### ISSUE TITLE
shown 3rd declension table for an adjective of 1st declension

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#74]
Lookup for diam. Whitaker output is:

di.am                N      1 1 ACC S F                 
dia, diae  N  F   [DEXFS]    Late  veryrare
goddess;
di.am                ADJ    1 1 ACC S F POS             
dius, dia, dium  ADJ   [DEXES]    Late  uncommon
divine; blessed, saint (Latham);

Click on Inflect, it opens the 3rd declension adjective table so there is no match. it should open the 1st declension adjective table.

same for bonus, nullus, miserrimus, primus

**Comment by balmas** [comment]
this looks to me to be working in the issue-inflection-tables-59 build of the webextension. Sending back to @monzug to verify.

**Comment by monzug** [comment]
it works for the adj listed above. however we have an issue with miserrimus because Whitaker split the word as following
miserri - mus
so we do not have any matches for this adj.
this issue will be added to a general Whitaker bug.
