### ISSUE TITLE
participles of irregular verbs should show full irregular table for that verb

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#76]
Reported by @monzug 

I think the move to treat verb participle forms as separate pofs has created a couple of unanticipated problems for the Latin irregular verb tables. 

In V1 we merged the data for participle and verb into a single table for the irregular verb

![screenshot from 2018-08-09 12-48-05](https://user-images.githubusercontent.com/644870/43913233-85043aac-9bd2-11e8-8f41-570b46612611.png)
![screenshot from 2018-08-09 12-48-12](https://user-images.githubusercontent.com/644870/43913243-8cd75322-9bd2-11e8-929a-bc4d618bfa53.png)

We have pulled the suffixes for participles, supines, gerundives out of the verb tables into their own part of speech now, which causes these to be in their own tables, which it seems make little sense outside of the context of the rest of irregular verb data.
E.g. for 'iens', the participle of 'eo` we get this:
![screenshot from 2018-08-09 12-51-35](https://user-images.githubusercontent.com/644870/43913442-fbef8c8e-9bd2-11e8-91a7-292c4a97d019.png)
(this may be further complicated by the fact that Whitaker calls the gerund  a participle, I'm not sure)

I think what we *want* to show for irregular verbs is a table that contains all of the endings for verbs, supines and gerundives. 

If it's a participle of an irregular verb, then we want to show the verb participle table and the full irregular verb table.

**Comment by balmas** [comment]
I think maybe option c is the one that fits best with the current code? This way we can keep them as separate, but linked, views? I.e. implement a rule that an irregular verb table includes as extra views all the views available for all forms of that irregular verb?

**Comment by kirlat** [comment]
Please test https://github.com/alpheios-project/inflection-tables/archive/%23infltbl-i76.zip to check a solution for that.
It seems that for supine and gerundive the only available feature data is case, so I edited CSV data files manually to reflect that and updated table rendering function so that it will produce tables with only one data column (it will have no column grouping features).

Please let me know if tables rendered are linguistically correct. Thanks!

**Comment by kirlat** [comment]
@monzug, please update a link to https://github.com/alpheios-project/webextension/archive/infltbl-i76.zip

**Comment by monzug** [comment]
a complicated issue. lets go step by step:
1) fix to how we display the table. we decide to show all verbal forms for irregular verb. if I enter eo (irregular verb) all tables are listed one after the other. this looks fine. However the change hasn't been  implemented for ientis or euntis which are verb participles of eo. There are two table generated: generic verb participle and the verb participle irregular. I think we wanted to show the irregular participle table and the option of the full irregular table. Am I correct on this one?

2) the participle table for eo is wrong. we need to update the content as follow:
a) PRESENT   iēns, euntis   -> footnote to say that euntis is gen.
    FUTURE   itūrus
b) then we have the GERUNDIVE for Allen& Greenough which is eundum   -> other grammars  ignore the gerundive. what do we want to do here? for Whitakers it's participle future passive (gerundive is by default passive) - My suggestion is to ignore the gerundive for now as we need further investigation to find common ground among all grammars and to update the current table by removing the Passive voice (we have the footnotes)   il presente è iens, euntis, il futuro iturus (passivo eundem)
c) we have the option to conjugate the participle, but haven't found much grammars implementing this. so it will be something like
nom. iens
gen. euntis.........

the participle table that I would suggest:

PARTICIPLES

PRESENT iēns, euntis  (footnotes)
FUTURE itūrus, eundum (footnotes)

**Comment by monzug** [comment]
forgot to say that also for the supine, we do not have the full irregular table generated but a complicated navigation through drop-downs. first I can chose from noun, verb participle and supine. if I chose supine, I have verb-irregular-supine and supine. I would prefer a simplify version of this navigation. 
noun
verb irregular --->  verb irregular supine
                               verb irregular  (where I can see the verb participle too)
what do you think?

**Comment by kirlat** [comment]
I do not have enough knowledge to decide how it's best to present inflection data, so I'll rely on you and Bridget here. But on my opinion drop-down navigation is complicated as it's hard to see all the choices at once, especially with dependent drop-downs for POSs (i.e. verbs have its own drop-downs for verb choices, but it changes for a different POS).

So what I want to offer for discussion if maybe we can stop using drop downs all together and maybe instead show titles of collapsed inflection tables we have on the word. "Main" tables can be shown expanded. That will allow users to see at once all tables that are available, and then expands the ones of interest to compare them side by side.

That would also be better UX-wise: expanding or collapsing a table requires a single click and using drop-downs require two (one to open a drop-down and another to make a click).

Please let me know what do you think.

**Comment by balmas** [comment]
recapping a Slack discussion with @kirlat on this issue:
point 1 ( "However the change hasn't been implemented for ientis or euntis which are verb participles of eo.") I think this is just the reverse of displaying the participle, gerundive and supine for an irregular verb  ... i.e the irregular verb form table needs to be linked to those tables and those tables need to link to the irregular verb form table. This should be fixed.

point 2a for the participle, even though our data has present and future forms, we are only showing the future. I think this is because the data file is missing the voice for the active forms. we should add 'active' in the voice column of those rows in the data file to fix this.

point 2b can be handled by commenting out the Gerundive view for now and we should do this

point 2c is for the future and should get a new issue created for it

re navigation: we should copy the comments on navigation to issue #23 which is where ordering and priority of inflection tables is requested.   I will add additional comments on that part of this request there.

**Comment by kirlat** [comment]
I added linked inflection tables for irregular verbs, verb participles, and supine. That should solve point 1.

I added missing voice for active forms, please verify if the updated data is correct. It seems this voice data was missing from the original XML file.
```
Lemma,PrincipalParts,Form,Voice,Mood,Tense,Number,Person,Footnote
sum,esse_fui_futurus,futūrus,active,,future,,,
sum,esse_fui_futurus,-a,active,,future,,,
sum,esse_fui_futurus,-um,active,,future,,,
fero,ferre_tuli_latus,ferēns,active,,present,,,
fero,ferre_tuli_latus,-entis,active,,present,,,
fero,ferre_tuli_latus,latūrus,active,,future,,,
fero,ferre_tuli_latus,ferundus,passive,,future,,,4
fero,ferre_tuli_latus,"lātus, -ta, -tum",passive,,perfect,,,8
volo,velle_volui_-,volēns,active,,present,,,
volo,velle_volui_-,-entis,active,,present,,,
eo,ire_ivi(ii)_itus,iēns,active,,present,,,
eo,ire_ivi(ii)_itus,euntis,active,,present,,,
eo,ire_ivi(ii)_itus,itūrus,active,,future,,,
eo,ire_ivi(ii)_itus,eundum,passive,,future,,,4
possum,posse_potui_-,potēns,active,,present,,,
```
This should solve 2a.

I temporarily removed gerundive tables from the rendering list. That should solve 2b for now.

You can use the same link to test an updated build: https://github.com/alpheios-project/webextension/archive/infltbl-i76.zip

Please let me know if there is anything else. Thanks!

**Comment by balmas** [comment]
this looks closer to me, a couple of points:

1. I'm not sure why euntis and iens, participles of fero, don't produce exact matches in the verb-participle-irregular table. these should be full form matches

2. the supine-irregular table shows the verb-participle-irregular table below it but not verb-irregular. It should have both (i.e. equivalent functionality to verb-participle-irregular which shows verb-irregular and supine-irregular below it)

3. I think we need to add an additional footnote to the participle data for eo but I will make that a separate issue.

**Comment by monzug** [comment]
why don't we have exact match also for itum (supine)?

**Comment by kirlat** [comment]
I submitted a fix that should correct a problem with form matches and with missing irregular verb table for supines. Build download link is the same: https://github.com/alpheios-project/webextension/archive/infltbl-i76.zip

Please let me know if there are any issues remaining. Thanks!

**Comment by monzug** [comment]
tested in Chrome
1)  euntis and iens, participles of eo, have exact matches in the irregular table. 
2) supine tables also show the irregular verb so now the navigation is simplified.

**Comment by kirlat** [comment]
https://github.com/alpheios-project/webextension/archive/infltbl-i167.zip should fix a regression reported in #167

**Comment by balmas** [comment]
I think first this fixes the missing tables for the participle (i.e. to match the supine).

**Comment by monzug** [comment]
still I do not see any changes:
![part1](https://user-images.githubusercontent.com/41396793/46086131-77338680-c175-11e8-8a2d-055dd8d14fe5.JPG)
![part2](https://user-images.githubusercontent.com/41396793/46086152-7e5a9480-c175-11e8-9b1d-25d01a350dca.JPG)

**Comment by kirlat** [comment]
Please check https://github.com/alpheios-project/webextension/archive/infltbl-i167.zip, it should fix it for "latum" (at least it works for me). That was a different issue related to this word which, I believe, I fixed now.
