### ISSUE TITLE
Miser and piger show 3rd adj decl table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#79]
white testing #59, I come across sample of adjective of the 2nd declension such as 
piger, pigra, pigrum
miser, misera, miserum
For the feminine and neuter endings we do have a match in the 1st and 2nd decl. adj. table. This table is called  first/second declension - stem in a and o
for miser and piger we show the 3rd adj. decl table. This table is called third declension, stem in
consonant and I

there are two problems here:
1) in all traditional latin grammar books, piger and miser are used as example of 2nd declension adjective.
2) the same adjective (according to our inflection table) can be 1st/2nd declension and 3rd declension, depending on the case and gender.
confusing.

**Comment by balmas** [comment]
I'm not sure what to do with this. Need advice from @abrasax

**Comment by monzug** [comment]
hope it's clear what is happening: miser goes to 3rd adj declension but
misera and miserum go to 1st/2nd declension adj table

**Comment by balmas** [comment]
yes, if I understand correctly, it goes to 3rd adj declension because there are matching (non) endings in that part of the table, and no matching endings in the 1st/2nd part of the table.  So, this would in part be addressed by #82 but there is a separate question here about why we don't get matches in 1st/2nd declension. Is our table wrong?

**Comment by monzug** [comment]
I think so. miser is the typical example of 2nd declension adj table
-er,a,um.  3rd decl adj are acer, brevis, audax. - we need to review the
source of these two tables.
I am honestly having some problems here with the scope of our project.
latin is a very structure dead language and the rules are set. I am not
sure if there is a new current that does a reinterpretation of the language
and its rules, and Harry is embrancing it. Do you have any inside info
about the choices made at the very beginning? do you think it's ok what I
am doing (checking the solidity of our tools versus the traditional
grammars) or should I just focus on the software more than on the content?

**Comment by balmas** [comment]
here the decision is to add the "-" empty ending to the 1st/2nd nominative and vocative m/n cells of the table.

Harry is going to send you the grammars he used for our tables, but the answer generally is that what you are doing is *exactly* what we want you to do -- nobody has done a thorough check on our data and we really need this.

**Comment by monzug** [comment]
Thanks. feel better now. I was a little "lost".

**Comment by monzug** [comment]
Fixed. Thanks. tested in Chrome and Firefox.
now it does not open the 3rd decl adj table for piger, miser or alter. 
however, I have two questions:
1) why irregular?
2) why also the neuter gender?

**Comment by balmas** [comment]
@monzug I don't understand either question...

**Comment by monzug** [comment]
the "-" empty ending has beed added to  to the 1st/2nd nominative and vocative m/n cells of the adj table.
why also neuter? and why has been added to the irregular column?

**Comment by balmas** [comment]
ah, if this is incorrect then it is my mistake. I thought that these were applicable to masculine and neuter and that they should be specified as irregular. If this is not the case then we should reopen the issue and I will fix those things. Thanks!

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-4

**Comment by monzug** [comment]
Looks good. Thanks
