### ISSUE TITLE
Superlatives and their stems according to Whitaker

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#80]
white testing #74 , I could not find a match for some superlatives such as miserrimus. in Whitaker the word is split as following:

miserri - mus

so we do not have any matches for this adj.

same for "pulcherrimus" ( pulcherri - mus )
pulcherri.mus        ADJ    1 2 NOM S M SUPER           
pulcher, pulchra -um, pulchrior -or -us, pulcherrimus -a -um  ADJ   [XXXAX]  
pretty; beautiful; handsome; noble, illustrious;

opti.mus             ADJ    1 1 NOM S M SUPER           
bonus, bona -um, melior -or -us, optimus -a -um  ADJ   [XXXAO]  
good, honest, brave, noble, kind, pleasant, right, useful; valid; healthy;

**Comment by balmas** [comment]
merging this with #82 -- sorry didn't see this one entered first!
