### ISSUE TITLE
can we use super instead of sup for the superlative adjective

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#81]
the first time I noticed sup, I thought of supine. Whitaker uses SUPER (all upper case).  I am ok with super (all lower case).

**Comment by balmas** [comment]
@abrasax I took the abbreviations for the various attributes from our Arethusa configuration files.  I'm not sure where those came from originally. Are you okay with using 'super' for this?

**Comment by balmas** [comment]
Per @abrasax we should change this to 'super'

**Comment by balmas** [comment]
fix committed to master via https://github.com/alpheios-project/data-models/pull/47 . Need to provide a build to test.

**Comment by balmas** [comment]
@monzug this can now be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-3

**Comment by monzug** [comment]
now it's super. Thx.
