### ISSUE TITLE
1st/2nd decl adj table has stem in a and o, 3rd decl has stem in consonant and i

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#88]
1st/2nd decl adj table has stem in a and o, 3rd decl has stem in consonant and i
in http://dcc.dickinson.edu/grammar/latin/formation-adjectives, they also use stem ending in -ro (e.g. miser) , gen in ius and dat in i (such as unus, una, unum).
do we need to specify the stem? and if we do, should we add the additional information (ending in ro and gen in ius)?

**Comment by balmas** [comment]
I have no idea about this.  Can we discuss?

**Comment by monzug** [comment]
Allen & Greenough also classified the adj by stem in -ro and gen in -ius:
1st and 2nd Declension Adjectives: Stems ending in -ro:
Stems ending in ro- preceded by e form the Nominative masculine like puer
1st and 2nd Declension Adjectives: Genitive in -īus, Dative in -ī
alius [aliud (n.)] other | tōtus whole | alter, -terīus the other
-- | -- | --
nūllus no, none | ūllus  any | neuter, -trīus neither
sōlus alone | ūnus  one | uter, -trīus which (of two)

as we do mention the stem in the adj inflection table, should we also add these stems?

**Comment by monzug** [comment]
@balmas shall we consider this for the next release?

**Comment by balmas** [comment]
sure, although I'm a little lost on what needs to be done... is this a data or a code change?

**Comment by monzug** [comment]
only data - I think it's only table title

**Comment by balmas** [comment]
ok, I will take this on as part of the Safari release then.

**Comment by monzug** [comment]
Most likely we can try to solve by adding a note and an ending - on the adj table for miser liber ...   and    niger pulcher ...

**Comment by monzug** [comment]
can we add a note to the masculine adjective 1st/2nd decl nominative regular ending in "-"? the note should say:

Stems ending in ro- preceded by e form the nominative masculine like miser, asper, gibber, lacer, liber, prosper (also prosperus), satur (-ura, -urum), tener; with compounds of -fer and -ger as saetige;, also usually dexter.
Stems in ro- preceded by a consonant form the nominative masculine like  niger, aeger, āter, crēber,  faber, glaber, integer, lūdicer, macer, piger, pulcher, ruber, sacer, scaber, sinister, taeter, vafer; also the possesives, noster, vester.


too long????

**Comment by balmas** [comment]
I will add it and you can see if you like it :-)

**Comment by monzug** [comment]
I was actually looking how to do it. basically you add a new number under
footnote in *suffixes.csv*  and then you add the text in *footnotes.csv*
correct?

**Comment by balmas** [comment]
yes :-)

**Comment by monzug** [comment]
I updated both files with 2 footnotes, 10 & 11 - could u pls check that I did ok? I am not sure if I was suppose to use the wrap mode as the line is looooong

**Comment by balmas** [comment]
close! I committed changes to each -- for the suffixes.csv, multiple footnote references should be separated by spaces and not commas. For footnotes.csv, it should be on a single line, the new lines will mess up the parser. 

I will go ahead and merge and the changes will be in the next build. thank you!

**Comment by monzug** [comment]
great. thanks for reviewing the changes.

**Comment by balmas** [comment]
I think you should be able to see this fix in build 2.1.0.9

**Comment by monzug** [comment]
all latin inflection table are messed up in latest build 2.1.0.9
hope I didn't do anything wrong by editing the data files.... et me know
please
see screenshot

**Comment by monzug** [comment]
tested in 2.1.0.10, verified
