### ISSUE TITLE
Fix the Supine table for Latin

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#90]
Branched from #82 
Per @monzug We need to fix the Supine table:

SUPINE
accusative -um
ablative -ū

no stem, no conjugation, no singular or plural, no active or passive. this is the supine.

**Comment by balmas** [comment]
@monzug this can now be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-3

**Comment by monzug** [comment]
I wish we could implement the easy version of the supine table. it would make life easier... A side effect of keeping the conjugation is the following:

1) 4th conjugation verbs have exact match in the 3rd conjugation column such as:
auditum and auditu 
vinctum and vinctu 
sensum and sensu
repertum and repertu

2) also the match for the supine of verb irregular goes to the 3rd conjugation column such as
latum and  latu
esum and  esu

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-5

**Comment by monzug** [comment]
much better. there are a couple of things that came up testing this fix. will open separate bus.
