### ISSUE TITLE
Perfect stem for 2nd conjugation should be changed to reflect traditional grammars

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#93]
see issue #84 
we should update the inflection table for the perfect stem of the 2nd conjugation active verbs so we can have matches on our table.
please remove all the -v in front of endings such as vi, veram, vero, verim, vissem
the correct endings should be -i, -eram, -ero, -erim, -issem
so we will have a match for monui, monueram, monuero, monuerim, pefect stem monu- 
suaserim, suasissem etc.  perfect stem suas-

**Comment by balmas** [comment]
Supine will be handled via #90

**Comment by balmas** [comment]
@monzug I think the 4th conjugation needs to be fixed too, right?

**Comment by balmas** [comment]
Need to make a build to test still

**Comment by monzug** [comment]
Yes. My task for tomorrow

**Comment by monzug** [comment]
Please remove the accent from the FUT PERF. - should be eris, erit, erimus, eritis, erint  (1st person singular is ok)
also the endings for the supine stem haven't been updated.

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-4

**Comment by monzug** [comment]
YES. fixed. thanks
