### ISSUE TITLE
accent to be added to -ēmini V  2 1 PRES PASSIVE IND 2 P 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#94]
second conjugation PASSIVE present indicative 2nd person Plural
mon.emini            V      2 1 PRES PASSIVE IND 2 P 
it should be -ēminī  accordingly to Allen & Greenough

**Comment by monzug** [comment]
and also to -ēbāmini 
mon.ebamini          V      2 1 IMPF PASSIVE IND 2 P 
it should be -ēbāminī

**Comment by balmas** [comment]
oh never mind, I was looking at the wrong letter...

**Comment by balmas** [comment]
Need to make a build to test still

**Comment by monzug** [comment]
Thanks for fixing it.
