### ISSUE TITLE
Please add following accents to verbs in the PASSIVE conjugations table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#96]
sis  should be sīs    1st conjugation subjunctive perfect 2nd p.s.
eras should be erās  1st conjugation Ind. pluperfect 2nd p.s.
esses should be essēs  1st conjugation subjunctive pluperfect 2nd p.s.

**Comment by balmas** [comment]
Need to make a build to test still

**Comment by monzug** [comment]
thanks for fixing this
