### ISSUE TITLE
Please correct these two endings in the 3rd conjugation table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#98]
-ēbas should be -ēbam   IMP.  INDIC. 1st person singular  active voice
-ēbāt  should be -ēbās    IMP.  INDIC. 2nd person singular active voice

**Comment by balmas** [comment]
@monzug this can now be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-3

**Comment by monzug** [comment]
fixed in build 2.0.2-3
